# Stubs for django.contrib.staticfiles.checks (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

from typing import Any, List
def check_finders(app_configs: None = ..., **kwargs: Any) -> List[Any]: ...
