# Stubs for django.contrib.staticfiles.urls (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

from django.urls.resolvers import URLPattern
from typing import List

urlpatterns: Any

def staticfiles_urlpatterns(prefix: None = ...) -> List[URLPattern]: ...
