from typing import Iterable, Iterator, Optional, Sequence

from django.core.files.storage import FileSystemStorage

def matches_patterns(path: str, patterns: Iterable[str]) -> bool: ...
def get_files(storage: FileSystemStorage, ignore_patterns: List[str] = ..., location: str = ...) -> Iterator[str]: ...
def check_settings(base_url: Optional[str] = ...) -> None: ...
