# Stubs for django.contrib.messages.context_processors (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from django.contrib.messages.storage.base import BaseStorage
from django.http.request import HttpRequest
from typing import Dict, Union
def messages(request: HttpRequest) -> Dict[str, Union[Dict[str, int], BaseStorage]]: ...
