# Stubs for django.contrib.messages.utils (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Dict
def get_level_tags() -> Dict[int, str]: ...
