# Stubs for django.urls.base (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .exceptions import NoReverseMatch, Resolver404
from .resolvers import get_ns_resolver, get_resolver
from .utils import get_callable
from typing import Any, Optional

from django.urls.resolvers import ResolverMatch
from typing import Any, Callable, Optional, Type, Union

_prefixes: Any
_urlconfs: Any

def resolve(path: str, urlconf: Optional[str] = ...) -> ResolverMatch: ...
def reverse(
    viewname: Optional[Union[str, Callable]],
    urlconf: Optional[str] = ...,
    args: Any = ...,
    kwargs: Any = ...,
    current_app: Optional[str] = ...,
) -> str: ...

reverse_lazy: Any

def clear_url_caches() -> None: ...
def set_script_prefix(prefix: str) -> None: ...
def get_script_prefix() -> str: ...
def clear_script_prefix() -> None: ...
def set_urlconf(urlconf_name: Optional[Union[Type[object], str]]) -> None: ...
def get_urlconf(default: None = ...) -> Optional[Union[str, Type[object]]]: ...
def is_valid_path(path: str, urlconf: Optional[str] = ...) -> bool: ...
def translate_url(url: str, lang_code: str) -> str: ...
