# Stubs for django.urls.conf (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .resolvers import (
    LocalePrefixPattern,
    RegexPattern,
    RoutePattern,
    URLPattern,
    URLResolver,
)
from typing import Any, Optional

from django.urls.resolvers import CheckURLMixin, URLPattern, URLResolver
from typing import Any, Optional, Type, Union

def include(arg: Any, namespace: Optional[str] = ...) -> Any: ...
def _path(
    route: str,
    view: Any,
    kwargs: Any = ...,
    name: Optional[str] = ...,
    Pattern: Type[CheckURLMixin] = ...,
) -> Union[URLPattern, URLResolver]: ...

path: Any
re_path: Any
