# Stubs for django.urls.utils (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from typing import Callable, Tuple, Union
def get_callable(lookup_view: Union[str, Callable]) -> Callable: ...
def get_mod_func(callback: str) -> Tuple[str, str]: ...
