from typing import Tuple


class DatabaseCreation:
    def _create_test_db(self, verbosity: int, autoclobber: bool, keepdb: bool = ...) -> str: ...
    def _destroy_test_db(self, test_database_name: str, verbosity: int) -> None: ...
    def _get_test_db_name(self) -> str: ...
    @staticmethod
    def is_in_memory_db(database_name: str) -> bool: ...
    def test_db_signature(self) -> Tuple[str, str]: ...