# Stubs for django.db.backends.postgresql.client (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.backends.base.client import BaseDatabaseClient
from typing import Any

from typing import Dict
def _escape_pgpass(txt: str) -> str: ...

class DatabaseClient(BaseDatabaseClient):
    executable_name: str = ...
    @classmethod
    def runshell_db(cls, conn_params: Dict[str, str]) -> None: ...
    def runshell(self) -> None: ...
