from typing import Any, Callable, Optional, Union


def cache_page(
    timeout: Union[float, int],
    *,
    cache: Optional[Any] = ...,
    key_prefix: Optional[Any] = ...
) -> Callable: ...
def cache_control(**kwargs: Any) -> Callable: ...
def never_cache(view_func: Callable) -> Callable: ...
