from collections.abc import Callable
from typing import Any

from . import _ViewFuncT

def cache_page(
    timeout: float | None, *, cache: Any | None = ..., key_prefix: Any | None = ...
) -> Callable[[_ViewFuncT], _ViewFuncT]: ...
def cache_control(**kwargs: Any) -> Callable[[_ViewFuncT], _ViewFuncT]: ...
def never_cache(view_func: _ViewFuncT, /) -> _ViewFuncT: ...
