# Stubs for django.views.decorators.csrf (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.middleware.csrf import CsrfViewMiddleware
from typing import Any

from django.http.request import HttpRequest
from typing import Any, Callable, Dict, Tuple
csrf_protect: Any

class _EnsureCsrfToken(CsrfViewMiddleware):
    def _reject(self, request: HttpRequest, reason: str) -> None: ...

requires_csrf_token: Any

class _EnsureCsrfCookie(CsrfViewMiddleware):
    def _reject(self, request: HttpRequest, reason: str) -> None: ...
    def process_view(self, request: HttpRequest, callback: Callable, callback_args: Tuple, callback_kwargs: Dict[Any, Any]) -> None: ...

ensure_csrf_cookie: Any

def csrf_exempt(view_func: Callable) -> Callable: ...
