from typing import Any, Optional, Tuple, Union

from django.db import models


class BaseUserManager(models.Manager):
    creation_counter: int
    model: None
    name: None
    @classmethod
    def normalize_email(cls, email: Optional[str]) -> str: ...
    def make_random_password(
        self, length: int = ..., allowed_chars: str = ...
    ) -> str: ...
    def get_by_natural_key(
        self, username: Optional[str]
    ) -> AbstractBaseUser: ...

class AbstractBaseUser(models.Model):
    password: str = ...
    last_login: None = ...
    is_active: bool = ...
    REQUIRED_FIELDS: Any = ...
    class Meta:
        abstract: bool = ...
    def get_username(self) -> str: ...
    def clean(self) -> None: ...
    def save(self, *args: Any, **kwargs: Any) -> None: ...
    def natural_key(self) -> Tuple[str]: ...
    @property
    def is_anonymous(self) -> bool: ...
    @property
    def is_authenticated(self) -> bool: ...
    def set_password(self, raw_password: Optional[str]) -> None: ...
    def check_password(self, raw_password: str) -> bool: ...
    def set_unusable_password(self) -> None: ...
    def has_usable_password(self) -> bool: ...
    def get_session_auth_hash(self) -> str: ...
    @classmethod
    def get_email_field_name(cls) -> str: ...
    @classmethod
    def normalize_username(
        cls, username: Union[int, str]
    ) -> Union[int, str]: ...
