from datetime import date
from django.contrib.auth.models import User
from typing import Optional


class PasswordResetTokenGenerator:
    def _make_hash_value(self, user: User, timestamp: int) -> str: ...
    def _make_token_with_timestamp(self, user: User, timestamp: int) -> str: ...
    def _num_days(self, dt: date) -> int: ...
    def _today(self) -> date: ...
    def check_token(self, user: User, token: Optional[str]) -> bool: ...
    def make_token(self, user: User) -> str: ...