from datetime import date, datetime
from typing import Any, Optional, Union

from django.contrib.auth.base_user import AbstractBaseUser

class PasswordResetTokenGenerator:
    key_salt: str = ...
    secret: Any = ...
    algorithm: str = ...
    def make_token(self, user: AbstractBaseUser) -> str: ...
    def check_token(self, user: Optional[AbstractBaseUser], token: Optional[str]) -> bool: ...
    def _make_token_with_timestamp(self, user: AbstractBaseUser, timestamp: int, legacy: bool = ...) -> str: ...
    def _make_hash_value(self, user: AbstractBaseUser, timestamp: int) -> str: ...
    def _num_seconds(self, dt: Union[datetime, date]) -> int: ...
    def _now(self) -> datetime: ...

default_token_generator: Any
