from typing import Any

from django.tasks.base import Task, TaskResult

from .base import BaseTaskBackend

class DummyBackend(BaseTaskBackend):
    results: list[TaskResult]
    def __init__(self, alias: str, params: dict[str, Any]) -> None: ...
    def enqueue(self, task: Task, args: list[Any], kwargs: dict[str, Any]) -> TaskResult: ...
    def get_result(self, result_id: str) -> TaskResult: ...
    async def aget_result(self, result_id: str) -> TaskResult: ...
    def clear(self) -> None: ...
