from django.core.checks.messages import Error
from django.db.models.query import QuerySet
from typing import List


class CurrentSiteManager:
    def __init__(self, field_name: None = ...) -> None: ...
    def _check_field_name(self) -> List[Error]: ...
    def _get_field_name(self) -> str: ...
    def check(self, **kwargs) -> List[Error]: ...
    def get_queryset(self) -> QuerySet: ...