# Regular configuration file (can be used as base in other projects, runs in CI)

[mypy]
# Modified in `tests.yml`
incremental = true

disallow_any_generics = true
strict = true
strict_equality_for_none = true
warn_unreachable = true

enable_error_code =
    deprecated,
    exhaustive-match,
    explicit-override,
    ignore-without-code,
    possibly-undefined,
    redundant-expr,
    redundant-self,
    truthy-bool,
    truthy-iterable,
    unimported-reveal,
    unused-awaitable,

fixed_format_cache = true
show_traceback = true

plugins =
    mypy_django_plugin.main,
    mypy.plugins.proper_plugin

# `tests/assert_type` uses bare generics on purpose, to test real world cases.
# The yml tests do too, they are handled in `scripts/tests_extension_hook.py`.
[mypy-tests.assert_type.*]
disallow_any_generics = false

# Our settings:
[mypy.plugins.django-stubs]
django_settings_module = scripts.django_tests_settings
