from typing import Any


class LogEntry:
    def __str__(self) -> str: ...
    def get_admin_url(self) -> str: ...
    def get_change_message(self) -> str: ...
    def is_addition(self) -> bool: ...
    def is_change(self) -> bool: ...
    def is_deletion(self) -> bool: ...


class LogEntryManager:
    def log_action(
        self,
        user_id: int,
        content_type_id: int,
        object_id: int,
        object_repr: str,
        action_flag: int,
        change_message: Any = ...
    ) -> LogEntry: ...