# Stubs for django.db.backends.mysql.client (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.backends.base.client import BaseDatabaseClient
from typing import Any

from typing import Dict, List, Optional

class DatabaseClient(BaseDatabaseClient):
    executable_name: str = ...
    @classmethod
    def settings_to_cmd_args(cls, settings_dict: Dict[str, Optional[str]]) -> List[str]: ...
    def runshell(self) -> None: ...
