# Stubs for django.db.migrations.operations.utils (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from django.db.migrations.state import ProjectState
from django.db.models.fields import Field

def is_referenced_by_foreign_key(
    state: ProjectState, model_name_lower: str, field: Field, field_name: str
) -> bool: ...
