# Stubs for django.core.checks.caches (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from django.core.checks.messages import Error
from typing import List

E001: Any

def check_default_cache_is_configured(app_configs: None, **kwargs: Any) -> List[Error]: ...
