from typing import Any, Callable, Dict, List, Optional, Tuple, Type, Union

from django.core.exceptions import FieldDoesNotExist as FieldDoesNotExist
from django.core.validators import EmailValidator, RegexValidator
from django.db.backends.sqlite3.base import DatabaseWrapper
from django.db.models.base import Model
from django.db.models.fields.reverse_related import ManyToOneRel
from django.db.models.query_utils import RegisterLookupMixin
from django.forms.fields import (DecimalField, Field, ImageField, IntegerField,
                                 TypedChoiceField, URLField)


class Empty: ...
class NOT_PROVIDED: ...

BLANK_CHOICE_DASH: Any

class Field(RegisterLookupMixin):
    empty_strings_allowed: bool = ...
    empty_values: Any = ...
    creation_counter: int = ...
    auto_creation_counter: int = ...
    default_validators: Any = ...
    default_error_messages: Any = ...
    system_check_deprecated_details: Any = ...
    system_check_removed_details: Any = ...
    hidden: bool = ...
    many_to_many: Any = ...
    many_to_one: Any = ...
    one_to_many: Any = ...
    one_to_one: Any = ...
    related_model: Any = ...
    description: Any = ...
    name: Any = ...
    verbose_name: Any = ...
    primary_key: Any = ...
    remote_field: Any = ...
    is_relation: Any = ...
    default: Any = ...
    editable: Any = ...
    serialize: Any = ...
    unique_for_date: Any = ...
    unique_for_month: Any = ...
    unique_for_year: Any = ...
    choices: Any = ...
    help_text: Any = ...
    db_index: Any = ...
    db_column: Any = ...
    auto_created: Any = ...
    error_messages: Any = ...
    def __init__(
        self,
        verbose_name: Optional[str] = ...,
        name: None = ...,
        primary_key: bool = ...,
        max_length: Optional[int] = ...,
        unique: bool = ...,
        blank: bool = ...,
        null: bool = ...,
        db_index: bool = ...,
        rel: Optional[ManyToOneRel] = ...,
        default: Union[Callable, Type[NOT_PROVIDED]] = ...,
        editable: bool = ...,
        serialize: bool = ...,
        unique_for_date: Optional[str] = ...,
        unique_for_month: Optional[str] = ...,
        unique_for_year: Optional[str] = ...,
        choices: Optional[
            Union[
                List[Tuple[str, str]],
                List[Tuple[int, str]],
                Tuple[Tuple[int, str], Tuple[int, str], Tuple[int, str]],
                Tuple[Tuple[str, str], Tuple[str, str]],
            ]
        ] = ...,
        help_text: str = ...,
        db_column: None = ...,
        db_tablespace: Optional[str] = ...,
        auto_created: bool = ...,
        validators: Union[List[RegexValidator], Tuple] = ...,
        error_messages: Optional[Dict[str, str]] = ...,
    ) -> None: ...
    def check(self, **kwargs: Any): ...
    def get_col(self, alias: Any, output_field: Optional[Any] = ...): ...
    def cached_col(self): ...
    def select_format(self, compiler: Any, sql: Any, params: Any): ...
    def deconstruct(
        self
    ) -> Union[
        Tuple[
            str,
            List[Any],
            Union[
                Dict[str, Union[int, List[RegexValidator], Dict[str, str]]],
                Dict[str, Union[bool, List[Tuple[int, str]]]],
                Dict[str, Union[Callable, List[Tuple[int, str]]]],
                Dict[str, int],
            ],
            Union[
                Dict[str, Union[int, List[RegexValidator], Dict[str, str]]],
                Dict[str, Union[bool, List[Tuple[int, str]]]],
                Dict[str, Union[Callable, List[Tuple[int, str]]]],
                Dict[str, int],
                Dict[Any, Any],
            ],
        ],
        Tuple[
            str,
            List[Any],
            Union[
                Dict[str, Union[int, Callable, List[Tuple[str, str]]]],
                Dict[str, Union[Callable, List[Tuple[int, str]]]],
                Dict[str, Union[int, List[RegexValidator], Dict[str, str]]],
            ],
            Union[
                Dict[str, Union[int, Callable, List[Tuple[str, str]]]],
                Dict[str, Union[Callable, List[Tuple[int, str]]]],
                Dict[str, Union[int, List[RegexValidator], Dict[str, str]]],
            ],
        ],
    ]: ...
    def clone(self) -> Field: ...
    def __eq__(self, other: CharField) -> bool: ...
    def __lt__(self, other: Field) -> bool: ...
    def __hash__(self): ...
    def __deepcopy__(self, memodict: Dict[Any, Any]) -> Field: ...
    def __copy__(self) -> Field: ...
    def __reduce__(self): ...
    def get_pk_value_on_save(self, instance: Model) -> None: ...
    def to_python(self, value: Any): ...
    def validators(
        self
    ) -> Union[List[RegexValidator], List[EmailValidator]]: ...
    def run_validators(self, value: Any): ...
    def validate(self, value: Any, model_instance: Any): ...
    def clean(self, value: Any, model_instance: Any): ...
    def db_type_parameters(self, connection: Any): ...
    def db_check(self, connection: Any): ...
    def db_type(self, connection: Any): ...
    def rel_db_type(self, connection: Any): ...
    def cast_db_type(self, connection: Any): ...
    def db_parameters(self, connection: Any): ...
    def db_type_suffix(self, connection: Any): ...
    def get_db_converters(self, connection: Any): ...
    @property
    def unique(self): ...
    @property
    def db_tablespace(self) -> str: ...
    concrete: Any = ...
    def set_attributes_from_name(self, name: str) -> None: ...
    model: Any = ...
    def contribute_to_class(
        self, cls: Type[Model], name: str, private_only: bool = ...
    ) -> None: ...
    def get_filter_kwargs_for_object(self, obj: Any): ...
    def get_attname(self) -> str: ...
    def get_attname_column(self) -> Tuple[str, str]: ...
    def get_internal_type(self): ...
    def pre_save(self, model_instance: Model, add: bool) -> Union[str, int]: ...
    def get_prep_value(self, value: Any): ...
    def get_db_prep_value(
        self, value: int, connection: DatabaseWrapper, prepared: bool = ...
    ) -> int: ...
    def get_db_prep_save(self, value: Any, connection: Any): ...
    def has_default(self) -> bool: ...
    def get_default(self): ...
    def get_choices(
        self,
        include_blank: bool = ...,
        blank_choice: List[Tuple[str, str]] = ...,
        limit_choices_to: None = ...,
    ) -> List[Tuple[str, str]]: ...
    def value_to_string(self, obj: Any): ...
    flatchoices: Any = ...
    def save_form_data(self, instance: Any, data: Any) -> None: ...
    def formfield(
        self,
        form_class: Type[Union[IntegerField, URLField, ImageField]] = ...,
        choices_form_class: None = ...,
        **kwargs: Any
    ) -> Field: ...
    def value_from_object(self, obj: Any): ...

class AutoField(Field):
    description: Any = ...
    empty_strings_allowed: bool = ...
    default_error_messages: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def check(self, **kwargs: Any): ...
    def deconstruct(self): ...
    def get_internal_type(self): ...
    def to_python(self, value: Any): ...
    def rel_db_type(self, connection: Any): ...
    def validate(self, value: Any, model_instance: Any) -> None: ...
    def get_db_prep_value(
        self, value: Any, connection: Any, prepared: bool = ...
    ): ...
    def get_prep_value(self, value: Any): ...
    def contribute_to_class(
        self, cls: Type[Model], name: str, **kwargs: Any
    ) -> None: ...
    def formfield(self, **kwargs: Any): ...

class BigAutoField(AutoField):
    description: Any = ...
    def get_internal_type(self): ...
    def rel_db_type(self, connection: Any): ...

class BooleanField(Field):
    empty_strings_allowed: bool = ...
    default_error_messages: Any = ...
    description: Any = ...
    def get_internal_type(self): ...
    def to_python(self, value: Any): ...
    def get_prep_value(self, value: Any): ...
    def formfield(self, **kwargs: Any): ...

class CharField(Field):
    description: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def check(self, **kwargs: Any): ...
    def cast_db_type(self, connection: Any): ...
    def get_internal_type(self): ...
    def to_python(self, value: Any): ...
    def get_prep_value(self, value: Any): ...
    def formfield(self, **kwargs: Any) -> URLField: ...

class CommaSeparatedIntegerField(CharField):
    default_validators: Any = ...
    description: Any = ...
    system_check_removed_details: Any = ...

class DateTimeCheckMixin:
    def check(self, **kwargs: Any): ...

class DateField(DateTimeCheckMixin, Field):
    empty_strings_allowed: bool = ...
    default_error_messages: Any = ...
    description: Any = ...
    def __init__(
        self,
        verbose_name: Optional[Any] = ...,
        name: Optional[Any] = ...,
        auto_now: bool = ...,
        auto_now_add: bool = ...,
        **kwargs: Any
    ) -> None: ...
    def deconstruct(self): ...
    def get_internal_type(self): ...
    def to_python(self, value: Any): ...
    def pre_save(self, model_instance: Any, add: Any): ...
    def contribute_to_class(
        self, cls: Type[Model], name: str, **kwargs: Any
    ) -> None: ...
    def get_prep_value(self, value: Any): ...
    def get_db_prep_value(
        self, value: Any, connection: Any, prepared: bool = ...
    ): ...
    def value_to_string(self, obj: Any): ...
    def formfield(self, **kwargs: Any): ...

class DateTimeField(DateField):
    empty_strings_allowed: bool = ...
    default_error_messages: Any = ...
    description: Any = ...
    def get_internal_type(self): ...
    def to_python(self, value: Any): ...
    def pre_save(self, model_instance: Any, add: Any): ...
    def get_prep_value(self, value: Any): ...
    def get_db_prep_value(
        self, value: Any, connection: Any, prepared: bool = ...
    ): ...
    def value_to_string(self, obj: Any): ...
    def formfield(self, **kwargs: Any): ...

class DecimalField(Field):
    empty_strings_allowed: bool = ...
    default_error_messages: Any = ...
    description: Any = ...
    def __init__(
        self,
        verbose_name: Optional[Any] = ...,
        name: Optional[Any] = ...,
        max_digits: Optional[Any] = ...,
        decimal_places: Optional[Any] = ...,
        **kwargs: Any
    ) -> None: ...
    def check(self, **kwargs: Any): ...
    def validators(self): ...
    def context(self): ...
    def deconstruct(self): ...
    def get_internal_type(self): ...
    def to_python(self, value: Any): ...
    def get_db_prep_save(self, value: Any, connection: Any): ...
    def get_prep_value(self, value: Any): ...
    def formfield(self, **kwargs: Any) -> DecimalField: ...

class DurationField(Field):
    empty_strings_allowed: bool = ...
    default_error_messages: Any = ...
    description: Any = ...
    def get_internal_type(self): ...
    def to_python(self, value: Any): ...
    def get_db_prep_value(
        self, value: Any, connection: Any, prepared: bool = ...
    ): ...
    def get_db_converters(self, connection: Any): ...
    def value_to_string(self, obj: Any): ...
    def formfield(self, **kwargs: Any): ...

class EmailField(CharField):
    default_validators: Any = ...
    description: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def deconstruct(self): ...
    def formfield(self, **kwargs: Any): ...

class FilePathField(Field):
    description: Any = ...
    def __init__(
        self,
        verbose_name: None = ...,
        name: None = ...,
        path: str = ...,
        match: str = ...,
        recursive: bool = ...,
        allow_files: bool = ...,
        allow_folders: bool = ...,
        **kwargs: Any
    ) -> None: ...
    def check(self, **kwargs: Any): ...
    def deconstruct(
        self
    ) -> Tuple[
        str, List[Any], Dict[str, Union[str, bool]], Dict[str, Union[str, bool]]
    ]: ...
    def get_prep_value(self, value: Any): ...
    def formfield(self, **kwargs: Any): ...
    def get_internal_type(self): ...

class FloatField(Field):
    empty_strings_allowed: bool = ...
    default_error_messages: Any = ...
    description: Any = ...
    def get_prep_value(self, value: Any): ...
    def get_internal_type(self): ...
    def to_python(self, value: Any): ...
    def formfield(self, **kwargs: Any): ...

class IntegerField(Field):
    empty_strings_allowed: bool = ...
    default_error_messages: Any = ...
    description: Any = ...
    def check(self, **kwargs: Any): ...
    def validators(self): ...
    def get_prep_value(self, value: Any): ...
    def get_internal_type(self): ...
    def to_python(self, value: Any): ...
    def formfield(self, **kwargs: Any) -> Field: ...

class BigIntegerField(IntegerField):
    empty_strings_allowed: bool = ...
    description: Any = ...
    MAX_BIGINT: int = ...
    def get_internal_type(self): ...
    def formfield(self, **kwargs: Any) -> IntegerField: ...

class IPAddressField(Field):
    empty_strings_allowed: bool = ...
    description: Any = ...
    system_check_removed_details: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def deconstruct(self): ...
    def get_prep_value(self, value: Any): ...
    def get_internal_type(self): ...

class GenericIPAddressField(Field):
    empty_strings_allowed: bool = ...
    description: Any = ...
    default_error_messages: Any = ...
    unpack_ipv4: Any = ...
    protocol: Any = ...
    def __init__(
        self,
        verbose_name: Optional[Any] = ...,
        name: Optional[Any] = ...,
        protocol: str = ...,
        unpack_ipv4: bool = ...,
        *args: Any,
        **kwargs: Any
    ) -> None: ...
    def check(self, **kwargs: Any): ...
    def deconstruct(self): ...
    def get_internal_type(self): ...
    def to_python(self, value: Any): ...
    def get_db_prep_value(
        self, value: Any, connection: Any, prepared: bool = ...
    ): ...
    def get_prep_value(self, value: Any): ...
    def formfield(self, **kwargs: Any): ...

class NullBooleanField(BooleanField):
    default_error_messages: Any = ...
    description: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def deconstruct(self): ...
    def get_internal_type(self): ...

class PositiveIntegerRelDbTypeMixin:
    def rel_db_type(self, connection: Any): ...

class PositiveIntegerField(PositiveIntegerRelDbTypeMixin, IntegerField):
    description: Any = ...
    def get_internal_type(self): ...
    def formfield(self, **kwargs: Any) -> TypedChoiceField: ...

class PositiveSmallIntegerField(PositiveIntegerRelDbTypeMixin, IntegerField):
    description: Any = ...
    def get_internal_type(self): ...
    def formfield(self, **kwargs: Any): ...

class SlugField(CharField):
    default_validators: Any = ...
    description: Any = ...
    allow_unicode: Any = ...
    def __init__(
        self,
        *args: Any,
        max_length: int = ...,
        db_index: bool = ...,
        allow_unicode: bool = ...,
        **kwargs: Any
    ) -> None: ...
    def deconstruct(self): ...
    def get_internal_type(self): ...
    def formfield(self, **kwargs: Any): ...

class SmallIntegerField(IntegerField):
    description: Any = ...
    def get_internal_type(self): ...

class TextField(Field):
    description: Any = ...
    def get_internal_type(self): ...
    def to_python(self, value: Any): ...
    def get_prep_value(self, value: Any): ...
    def formfield(self, **kwargs: Any): ...

class TimeField(DateTimeCheckMixin, Field):
    empty_strings_allowed: bool = ...
    default_error_messages: Any = ...
    description: Any = ...
    def __init__(
        self,
        verbose_name: Optional[Any] = ...,
        name: Optional[Any] = ...,
        auto_now: bool = ...,
        auto_now_add: bool = ...,
        **kwargs: Any
    ) -> None: ...
    def deconstruct(self): ...
    def get_internal_type(self): ...
    def to_python(self, value: Any): ...
    def pre_save(self, model_instance: Any, add: Any): ...
    def get_prep_value(self, value: Any): ...
    def get_db_prep_value(
        self, value: Any, connection: Any, prepared: bool = ...
    ): ...
    def value_to_string(self, obj: Any): ...
    def formfield(self, **kwargs: Any): ...

class URLField(CharField):
    default_validators: Any = ...
    description: Any = ...
    def __init__(
        self,
        verbose_name: Optional[Any] = ...,
        name: Optional[Any] = ...,
        **kwargs: Any
    ) -> None: ...
    def deconstruct(self): ...
    def formfield(self, **kwargs: Any): ...

class BinaryField(Field):
    description: Any = ...
    empty_values: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def deconstruct(self): ...
    def get_internal_type(self): ...
    def get_placeholder(self, value: Any, compiler: Any, connection: Any): ...
    def get_default(self): ...
    def get_db_prep_value(
        self, value: Any, connection: Any, prepared: bool = ...
    ): ...
    def value_to_string(self, obj: Any): ...
    def to_python(self, value: Any): ...

class UUIDField(Field):
    default_error_messages: Any = ...
    description: str = ...
    empty_strings_allowed: bool = ...
    def __init__(
        self, verbose_name: Optional[Any] = ..., **kwargs: Any
    ) -> None: ...
    def deconstruct(self): ...
    def get_internal_type(self): ...
    def get_db_prep_value(
        self, value: Any, connection: Any, prepared: bool = ...
    ): ...
    def to_python(self, value: Any): ...
    def formfield(self, **kwargs: Any): ...
