# Stubs for django.db.models.fields.proxy (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.models import fields
from typing import Any

class OrderWrt(fields.IntegerField):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
