from typing import Any, Optional

from django.db.models.lookups import (Exact, GreaterThan, GreaterThanOrEqual,
                                      In, IsNull, LessThan, LessThanOrEqual)


class MultiColSource:
    contains_aggregate: bool = ...
    output_field: Any = ...
    def __init__(
        self, alias: Any, targets: Any, sources: Any, field: Any
    ) -> None: ...
    def relabeled_clone(self, relabels: Any): ...
    def get_lookup(self, lookup: Any): ...

def get_normalized_value(value: Any, lhs: Any): ...

class RelatedIn(In):
    rhs: Any = ...
    def get_prep_lookup(self): ...
    def as_sql(self, compiler: Any, connection: Any): ...

class RelatedLookupMixin:
    rhs: Any = ...
    def get_prep_lookup(self): ...
    def as_sql(self, compiler: Any, connection: Any): ...

class RelatedExact(RelatedLookupMixin, Exact): ...
class RelatedLessThan(RelatedLookupMixin, LessThan): ...
class RelatedGreaterThan(RelatedLookupMixin, GreaterThan): ...
class RelatedGreaterThanOrEqual(RelatedLookupMixin, GreaterThanOrEqual): ...
class RelatedLessThanOrEqual(RelatedLookupMixin, LessThanOrEqual): ...
class RelatedIsNull(RelatedLookupMixin, IsNull): ...
