from typing import Any

from django.db.models.fields import CharField, EmailField, TextField

class CIText: ...
class CICharField(CIText, CharField[Any, Any]): ...
class CIEmailField(CIText, EmailField[Any, Any]): ...
class CITextField(CIText, TextField[Any, Any]): ...
