from typing import Any

from django.db import models

class RangeField(models.Field):
    empty_strings_allowed: bool = ...
    base_field: Any = ...
    range_type: Any = ...
    def get_prep_value(self, value: Any): ...
    def to_python(self, value: Any): ...
    def value_to_string(self, obj: Any): ...

class IntegerRangeField(RangeField): ...
class BigIntegerRangeField(RangeField): ...
class FloatRangeField(RangeField): ...
class DateTimeRangeField(RangeField): ...
class DateRangeField(RangeField): ...
