from typing import Any

from django.db import models

class RangeField(models.Field):
    empty_strings_allowed: bool = ...
    base_field: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def model(self): ...
    @model.setter
    def model(self, model: Any) -> None: ...
    def get_prep_value(self, value: Any): ...
    def to_python(self, value: Any): ...
    def set_attributes_from_name(self, name: str) -> None: ...
    def value_to_string(self, obj: Any): ...
    def formfield(self, **kwargs: Any): ...

class IntegerRangeField(RangeField):
    base_field: Any = ...
    range_type: Any = ...
    form_field: Any = ...
    def db_type(self, connection: Any): ...

class BigIntegerRangeField(RangeField):
    base_field: Any = ...
    range_type: Any = ...
    form_field: Any = ...
    def db_type(self, connection: Any): ...

class FloatRangeField(RangeField):
    base_field: Any = ...
    range_type: Any = ...
    form_field: Any = ...
    def db_type(self, connection: Any): ...

class DateTimeRangeField(RangeField):
    base_field: Any = ...
    range_type: Any = ...
    form_field: Any = ...
    def db_type(self, connection: Any): ...

class DateRangeField(RangeField):
    base_field: Any = ...
    range_type: Any = ...
    form_field: Any = ...
    def db_type(self, connection: Any): ...
