from typing import Dict


def get_internal_wsgi_application() -> object: ...


class WSGIRequestHandler:
    def address_string(self) -> str: ...
    def get_environ(self) -> Dict[str, str]: ...
    def log_message(self, format: str, *args) -> None: ...