from django.db.models.base import Model
from typing import (
    Any,
    Iterator,
    Type,
)


class AppConfig:
    def __init__(self, app_name: str, app_module: Any) -> None: ...
    def _path_from_module(self, module: Any) -> str: ...
    @classmethod
    def create(cls, entry: str) -> AppConfig: ...
    def get_model(self, model_name: str, require_ready: bool = ...) -> Type[Model]: ...
    def get_models(
        self,
        include_auto_created: bool = ...,
        include_swapped: bool = ...
    ) -> Iterator[Type[Model]]: ...
    def import_models(self) -> None: ...
    def ready(self) -> None: ...