from django.template.defaulttags import TemplateLiteral
from typing import (
    Any,
    Dict,
    List,
    Optional,
    Union,
)


class IfParser:
    def __init__(self, tokens: Any) -> None: ...
    def create_var(self, value: Optional[Union[List[int], int]]) -> Literal: ...
    def expression(self, rbp: int = ...) -> Literal: ...
    def next_token(self) -> Literal: ...
    def parse(self) -> TemplateLiteral: ...
    def translate_token(self, token: Union[List[int], str, int]) -> Literal: ...


class Literal:
    def __init__(self, value: Optional[int]) -> None: ...
    def __repr__(self) -> str: ...
    def eval(self, context: Dict[Any, Any]) -> Optional[Union[int, List[int]]]: ...
    def nud(self, parser: IfParser) -> Literal: ...