from typing import Any, Optional

class BaseEmailBackend:
    fail_silently: Any = ...
    def __init__(self, fail_silently: bool = ..., **kwargs: Any) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> BaseEmailBackend: ...
    def __exit__(self, exc_type: None, exc_value: None, traceback: None) -> None: ...
    def send_messages(self, email_messages: Any) -> None: ...
