from typing import Any, Optional

from django.core.mail.backends.console import EmailBackend as ConsoleEmailBackend
from django.core.mail.message import EmailMessage

class EmailBackend(ConsoleEmailBackend):
    fail_silently: bool
    file_path: str = ...
    def __init__(self, *args: Any, file_path: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def write_message(self, message: EmailMessage) -> None: ...
    stream: None = ...
    def open(self) -> bool: ...
    def close(self) -> None: ...
