from django.db.backends.sqlite3.base import DatabaseWrapper
from typing import (
    Dict,
    Optional,
    Tuple,
    Union,
)


class BaseDatabaseCreation:
    def __init__(self, connection: DatabaseWrapper) -> None: ...
    def _get_database_display_str(self, verbosity: int, database_name: str) -> str: ...
    def _get_test_db_name(self) -> str: ...
    def create_test_db(
        self,
        verbosity: int = ...,
        autoclobber: bool = ...,
        serialize: bool = ...,
        keepdb: bool = ...
    ) -> str: ...
    def deserialize_db_from_string(self, data: str) -> None: ...
    def destroy_test_db(
        self,
        old_database_name: str = ...,
        verbosity: int = ...,
        keepdb: bool = ...,
        suffix: None = ...
    ) -> None: ...
    def serialize_db_to_string(self) -> str: ...
    def set_as_test_mirror(self, primary_settings_dict: Dict[str, Optional[Union[str, int, Dict[str, None]]]]) -> None: ...
    def test_db_signature(self) -> Tuple[str, str, str, str]: ...