# Stubs for django.db.backends.base.validation (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from django.db.backends.base.base import BaseDatabaseWrapper
from django.db.models.fields import Field
from typing import Any, List

class BaseDatabaseValidation:
    connection: Any = ...
    def __init__(self, connection: BaseDatabaseWrapper) -> None: ...
    def check(self, **kwargs: Any): ...
    def check_field(self, field: Field, **kwargs: Any) -> List[Any]: ...
