from django.core.management.base import CommandParser
from typing import List, Tuple, Union

def humanize(dirname: str) -> str: ...

class Command:
    def add_arguments(self, parser: CommandParser) -> None: ...
    def find_fixtures(self, fixture_label: str) -> List[Tuple[str, str, str]]: ...
    @cached_property
    def fixture_dirs(self) -> List[str]: ...
    def handle(self, *fixture_labels, **options) -> None: ...
    def load_label(self, fixture_label: str) -> None: ...
    def loaddata(self, fixture_labels: Union[Tuple[str, str], Tuple[str]]) -> None: ...
    def parse_name(
        self, fixture_name: str
    ) -> Union[Tuple[str, None, None], Tuple[str, str, None], Tuple[str, str, str]]: ...

class SingleZipReader:
    def read(self) -> bytes: ...
