from django.core.management.base import CommandParser
from django.db.backends.sqlite3.base import DatabaseWrapper
from django.db.migrations.loader import MigrationLoader
from typing import List


class Command:
    def _validate_app_names(self, loader: MigrationLoader, app_names: List[str]) -> None: ...
    def add_arguments(self, parser: CommandParser) -> None: ...
    def handle(self, *args, **options) -> None: ...
    def show_list(
        self,
        connection: DatabaseWrapper,
        app_names: List[str] = ...
    ) -> None: ...
    def show_plan(
        self,
        connection: DatabaseWrapper,
        app_names: List[str] = ...
    ) -> None: ...