from django.core.mail.message import EmailMessage


class EmailBackend:
    def __init__(self, *args, file_path = ..., **kwargs) -> None: ...
    def _get_filename(self) -> str: ...
    def close(self) -> None: ...
    def open(self) -> bool: ...
    def write_message(self, message: EmailMessage) -> None: ...