# Stubs for django.core.mail.backends.locmem (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.core.mail.backends.base import BaseEmailBackend
from typing import Any

from django.core.mail.message import EmailMessage, EmailMultiAlternatives
from typing import List, Union

class EmailBackend(BaseEmailBackend):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def send_messages(
        self, messages: Union[List[EmailMultiAlternatives], List[EmailMessage]]
    ) -> int: ...
