# Stubs for django.core.cache.utils (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

from typing import List, Optional, Union
TEMPLATE_FRAGMENT_KEY_TEMPLATE: str

def make_template_fragment_key(fragment_name: str, vary_on: Optional[Union[List[int], List[str]]] = ...) -> str: ...
