# Stubs for django.contrib.admindocs.middleware (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .utils import get_view_name
from django.utils.deprecation import MiddlewareMixin
from typing import Any

from django.core.handlers.wsgi import WSGIRequest
from django.http.response import HttpResponse
from typing import Any, Callable, Dict, Optional, Tuple
class XViewMiddleware(MiddlewareMixin):
    def process_view(self, request: WSGIRequest, view_func: Callable, view_args: Tuple, view_kwargs: Dict[Any, Any]) -> Optional[HttpResponse]: ...
