# Stubs for django.views.defaults (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from django.core.exceptions import PermissionDenied, SuspiciousOperation
from django.core.handlers.wsgi import WSGIRequest
from django.http.response import (
    Http404,
    HttpResponseBadRequest,
    HttpResponseForbidden,
    HttpResponseNotFound,
    HttpResponseServerError,
)
from typing import Optional

ERROR_404_TEMPLATE_NAME: str
ERROR_403_TEMPLATE_NAME: str
ERROR_400_TEMPLATE_NAME: str
ERROR_500_TEMPLATE_NAME: str

def page_not_found(
    request: WSGIRequest, exception: Optional[Http404], template_name: str = ...
) -> HttpResponseNotFound: ...
def server_error(
    request: WSGIRequest, template_name: str = ...
) -> HttpResponseServerError: ...
def bad_request(
    request: WSGIRequest, exception: SuspiciousOperation, template_name: str = ...
) -> HttpResponseBadRequest: ...
def permission_denied(
    request: WSGIRequest, exception: PermissionDenied, template_name: str = ...
) -> HttpResponseForbidden: ...
