# Stubs for django.views.static (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

from django.core.handlers.wsgi import WSGIRequest
from django.http.response import FileResponse, HttpResponse
from pathlib import PosixPath
from typing import Optional, Union

def serve(
    request: WSGIRequest, path: str, document_root: str = ..., show_indexes: bool = ...
) -> Union[HttpResponse, FileResponse]: ...

DEFAULT_DIRECTORY_INDEX_TEMPLATE: str
template_translatable: Any

def directory_index(path: str, fullpath: PosixPath) -> HttpResponse: ...
def was_modified_since(
    header: Optional[str] = ..., mtime: float = ..., size: int = ...
) -> bool: ...
