# Stubs for django (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

VERSION: Any
__version__: Any

def setup(set_prefix: bool = ...) -> None: ...
