from typing import Any, ClassVar

from django.db import models
from django.db.models import Func, Transform
from django.db.models.expressions import Combinable, Expression, Value

class MySQLSHA2Mixin: ...
class OracleHashMixin: ...
class PostgreSQLSHAMixin: ...
class Chr(Transform): ...

class ConcatPair(Func):
    def coalesce(self) -> ConcatPair: ...

class Concat(Func):
    def __init__(self, *expressions: Any, **extra: Any) -> None: ...

class Left(Func):
    output_field: ClassVar[models.CharField]
    def __init__(self, expression: Expression | str, length: Expression | int, **extra: Any) -> None: ...
    def get_substr(self) -> Substr: ...

class Length(Transform):
    output_field: ClassVar[models.IntegerField]

class Lower(Transform): ...

class LPad(Func):
    output_field: ClassVar[models.CharField]
    def __init__(
        self, expression: Expression | str, length: Expression | int | None, fill_text: Expression = ..., **extra: Any
    ) -> None: ...

class LTrim(Transform): ...
class MD5(OracleHashMixin, Transform): ...

class Ord(Transform):
    output_field: ClassVar[models.IntegerField]

class Repeat(Func):
    output_field: ClassVar[models.CharField]
    def __init__(self, expression: Expression | str, number: Expression | int | None, **extra: Any) -> None: ...

class Replace(Func):
    def __init__(self, expression: Combinable | str, text: Value, replacement: Value = ..., **extra: Any) -> None: ...

class Reverse(Transform): ...

class Right(Left):
    def get_substr(self) -> Substr: ...

class RPad(LPad): ...
class RTrim(Transform): ...
class SHA1(OracleHashMixin, PostgreSQLSHAMixin, Transform): ...
class SHA224(MySQLSHA2Mixin, PostgreSQLSHAMixin, Transform): ...
class SHA256(MySQLSHA2Mixin, OracleHashMixin, PostgreSQLSHAMixin, Transform): ...
class SHA384(MySQLSHA2Mixin, OracleHashMixin, PostgreSQLSHAMixin, Transform): ...
class SHA512(MySQLSHA2Mixin, OracleHashMixin, PostgreSQLSHAMixin, Transform): ...

class StrIndex(Func):
    output_field: ClassVar[models.IntegerField]

class Substr(Func):
    output_field: ClassVar[models.CharField]
    def __init__(
        self, expression: Expression | str, pos: Expression | int, length: Expression | int | None = ..., **extra: Any
    ) -> None: ...

class Trim(Transform): ...
class Upper(Transform): ...
