# Stubs for django.contrib.humanize.templatetags.humanize (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

from datetime import date, datetime
from typing import Optional, Union

register: Any

def ordinal(value: Optional[str]) -> Optional[str]: ...
def intcomma(value: Optional[Union[str, float]], use_l10n: bool = ...) -> str: ...

intword_converters: Any

def intword(value: Optional[str]) -> Optional[str]: ...
def apnumber(value: str) -> str: ...
def naturalday(value: Optional[date], arg: None = ...) -> Optional[str]: ...
def naturaltime(value: datetime) -> str: ...
