from typing import (
    Any,
    Dict,
    List,
)


class Model:
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> Dict[str, Any]: ...
    def __hash__(self) -> int: ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: Dict[str, Any]) -> None: ...
    def __str__(self) -> str: ...
    @classmethod
    def _check_column_name_clashes(cls) -> List[Any]: ...