from django.db.backends.ddl_references import Statement
from django.db.backends.sqlite3.schema import DatabaseSchemaEditor
from django.db.models.base import Model
from typing import (
    Any,
    Dict,
    List,
    Tuple,
    Type,
    Union,
)


class Index:
    def __eq__(self, other: Index) -> bool: ...
    def __init__(self, *, fields = ..., name = ..., db_tablespace = ...) -> None: ...
    @staticmethod
    def _hash_generator(*args) -> str: ...
    def check_name(self) -> List[Any]: ...
    def clone(self) -> Index: ...
    def create_sql(
        self,
        model: Type[Model],
        schema_editor: DatabaseSchemaEditor,
        using: str = ...
    ) -> Statement: ...
    def deconstruct(self) -> Tuple[str, Tuple, Dict[str, Union[List[str], str]]]: ...
    def set_name_with_model(self, model: Type[Model]) -> None: ...