from django.utils.datastructures import ImmutableList
from typing import (
    Any,
    Dict,
)


class Options:
    def __init__(self, meta: Any, app_label: str = ...) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def _expire_cache(self, forward: bool = ..., reverse: bool = ...) -> None: ...
    @cached_property
    def _forward_fields_map(self) -> Dict[str, Any]: ...
    def _get_fields(
        self,
        forward: bool = ...,
        reverse: bool = ...,
        include_parents: object = ...,
        include_hidden: bool = ...,
        seen_models: Any = ...
    ) -> ImmutableList: ...
    def _populate_directed_relation_graph(self) -> Any: ...
    def _prepare(self, model: Any) -> None: ...