from typing import Any, Optional

from django.db import models


class FlatPage(models.Model):
    id: None
    url: str = ...
    title: str = ...
    content: str = ...
    enable_comments: bool = ...
    template_name: str = ...
    registration_required: bool = ...
    sites: Any = ...
    class Meta:
        db_table: str = ...
        verbose_name: Any = ...
        verbose_name_plural: Any = ...
        ordering: Any = ...
    def get_absolute_url(self) -> str: ...
