from typing import Any, Optional

from django.db import models

class FlatPage(models.Model):
    id: None
    url: str = ...
    title: str = ...
    content: str = ...
    enable_comments: bool = ...
    template_name: str = ...
    registration_required: bool = ...
    sites: Any = ...
    def get_absolute_url(self) -> str: ...
