# Stubs for django.contrib.flatpages.sitemaps (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.contrib.sitemaps import Sitemap

from django.db.models.query import QuerySet
class FlatPageSitemap(Sitemap):
    def items(self) -> QuerySet: ...
