def auth_password_validators_changed(**kwargs) -> None: ...


def clear_cache_handlers(**kwargs) -> None: ...


def clear_routers_cache(**kwargs) -> None: ...


def clear_serializers_cache(**kwargs) -> None: ...


def complex_setting_changed(**kwargs) -> None: ...


def file_storage_changed(**kwargs) -> None: ...


def language_changed(**kwargs) -> None: ...


def localize_settings_changed(**kwargs) -> None: ...


def reset_template_engines(**kwargs) -> None: ...


def root_urlconf_changed(**kwargs) -> None: ...


def static_finders_changed(**kwargs) -> None: ...


def static_storage_changed(**kwargs) -> None: ...


def update_connections_time_zone(**kwargs) -> None: ...


def update_installed_apps(**kwargs) -> None: ...


def user_model_swapped(**kwargs) -> None: ...