# Stubs for django.contrib.contenttypes.apps (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .management import create_contenttypes, inject_rename_contenttypes_operations
from django.apps import AppConfig
from typing import Any

class ContentTypesConfig(AppConfig):
    name: str = ...
    verbose_name: Any = ...
    def ready(self) -> None: ...
