# Stubs for django.template.loaders.app_directories (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .filesystem import Loader as FilesystemLoader

from typing import Tuple, Union

class Loader(FilesystemLoader):
    def get_dirs(
        self
    ) -> Union[
        Tuple[str, str], Tuple[str, str, str], Tuple[str], Tuple[str, str, str, str]
    ]: ...
