from pathlib import Path
from typing import Iterator, List

from django.template.base import Origin
from django.template.engine import Engine

from .base import Loader as BaseLoader

class Loader(BaseLoader):
    dirs: List[str | Path] | None = ...
    def __init__(self, engine: Engine, dirs: List[str | Path] | None = ...) -> None: ...
    def get_dirs(self) -> List[str | Path]: ...
    def get_contents(self, origin: Origin) -> str: ...
    def get_template_sources(self, template_name: str) -> Iterator[Origin]: ...
