from typing import Iterator, List, Optional

from django.template.base import Origin
from django.template.engine import Engine

from .base import Loader as BaseLoader

class Loader(BaseLoader):
    dirs: Optional[List[str]] = ...
    def __init__(self, engine: Engine, dirs: Optional[List[str]] = ...) -> None: ...
    def get_dirs(self) -> List[str]: ...
    def get_contents(self, origin: Origin) -> str: ...
    def get_template_sources(self, template_name: str) -> Iterator[Origin]: ...
