from typing import Any, Iterator, List, Optional, Union

from django.template.base import Origin
from django.template.engine import Engine

from .base import Loader as BaseLoader

class Loader(BaseLoader):
    engine: Engine
    dirs: Optional[List[str]] = ...
    def __init__(self, engine: Engine, dirs: Optional[List[str]] = ...) -> None: ...
    def get_dirs(self) -> Union[List[bytes], List[str]]: ...
    def get_contents(self, origin: Origin) -> Any: ...
    def get_template_sources(self, template_name: Union[bytes, str]) -> Iterator[Origin]: ...
