# Stubs for django.template.loaders.locmem (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import Loader as BaseLoader
from typing import Any

from django.template.base import Origin
from django.template.engine import Engine
from typing import Dict, Iterator
class Loader(BaseLoader):
    templates_dict: Any = ...
    def __init__(self, engine: Engine, templates_dict: Dict[str, str]) -> None: ...
    def get_contents(self, origin: Origin) -> str: ...
    def get_template_sources(self, template_name: str) -> Iterator[Origin]: ...
