from django import forms
from typing import Any, Type, Union

class InvalidJSONInput(str): ...
class JSONString(str): ...

class JSONField(forms.CharField):
    widget: Union[forms.Widget, Type[forms.Widget]] = ...
    def prepare_value(self, value: Any) -> str: ...
