# Stubs for django.http.cookie (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from typing import Dict
SimpleCookie: Any

def parse_cookie(cookie: str) -> Dict[str, str]: ...
