from html.parser import HTMLParser
from typing import Any, List, Optional, Tuple, Union

WHITESPACE: Any

def normalize_whitespace(string: str) -> str: ...

class Element:
    name: str = ...
    attributes: List[Tuple[str, Optional[str]]] = ...
    children: List[Union[django.test.html.Element, str]] = ...
    def __init__(
        self,
        name: Optional[str],
        attributes: Union[List[Tuple[str, Union[str, None]]], Tuple],
    ) -> None: ...
    def append(self, element: Union[str, Element]) -> None: ...
    def finalize(self) -> None: ...
    def __eq__(self, element: Element) -> bool: ...
    def __hash__(self) -> int: ...
    def __contains__(self, element: Union[str, Element]) -> bool: ...
    def count(self, element: Union[str, Element]) -> int: ...
    def __getitem__(self, key: int) -> Union[str, Element]: ...

class RootElement(Element):
    attributes: List[Any]
    children: List[Union[django.test.html.Element, str]]
    name: None
    def __init__(self) -> None: ...

class HTMLParseError(Exception): ...

class Parser(HTMLParser):
    SELF_CLOSING_TAGS: Any = ...
    root: Any = ...
    open_tags: Any = ...
    element_positions: Any = ...
    def __init__(self) -> None: ...
    def error(self, msg: str) -> Any: ...
    def format_position(
        self, position: None = ..., element: None = ...
    ) -> str: ...
    @property
    def current(self) -> Element: ...
    def handle_startendtag(
        self, tag: str, attrs: List[Tuple[str, Optional[str]]]
    ) -> None: ...
    def handle_starttag(
        self, tag: str, attrs: List[Tuple[str, Optional[str]]]
    ) -> None: ...
    def handle_endtag(self, tag: str) -> None: ...
    def handle_data(self, data: str) -> None: ...
    def handle_charref(self, name: str) -> None: ...
    def handle_entityref(self, name: str) -> None: ...

def parse_html(html: str) -> Element: ...
