# Stubs for django.contrib.sessions.middleware (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.deprecation import MiddlewareMixin
from typing import Any, Optional

from django.core.handlers.wsgi import WSGIRequest
from django.http.response import HttpResponseBase
from typing import Callable, Optional

class SessionMiddleware(MiddlewareMixin):
    get_response: Any = ...
    SessionStore: Any = ...
    def __init__(self, get_response: Optional[Callable] = ...) -> None: ...
    def process_request(self, request: WSGIRequest) -> None: ...
    def process_response(
        self, request: WSGIRequest, response: HttpResponseBase
    ) -> HttpResponseBase: ...
