# Stubs for django.contrib.sessions.serializers (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.core.signing import JSONSerializer as BaseJSONSerializer
from typing import Any

from datetime import datetime
from django.db.models.base import Model
from typing import Dict, Union

class PickleSerializer:
    def dumps(self, obj: Dict[str, Union[str, datetime]]) -> bytes: ...
    def loads(self, data: bytes) -> Dict[str, Model]: ...

JSONSerializer = BaseJSONSerializer
