class BaseEmailBackend:
    def __enter__(self) -> BaseEmailBackend: ...
    def __exit__(self, exc_type: None, exc_value: None, traceback: None) -> None: ...
    def __init__(self, fail_silently: bool = ..., **kwargs) -> None: ...
    def close(self) -> None: ...
    def open(self) -> None: ...