#!/bin/sh

set -ex


# format code
if [[ $CI ]]; then
    ./.venv/bin/black --check tests typings
    ./.venv/bin/isort --check-only tests typings
else
    ./.venv/bin/black tests typings
    ./.venv/bin/isort tests typings
fi

# type check code
./.venv/bin/mypy tests typings


# TODO(sbdchd): re-enable once the latest pyright ships
if [[ -z $CI ]]; then
    ./node_modules/.bin/pyright typings
fi

# lint
./.venv/bin/flake8 tests typings
