#!/bin/sh

set -ex

if [[ ! -f ./.venv/lib/python3.7/site-packages/django-stubs.egg-link ]]; then
  ./.venv/bin/pip install -e .
fi


# format code
if [[ $CI ]]; then
    ./.venv/bin/black --check tests typings
    ./.venv/bin/isort --check-only tests typings
else
    ./.venv/bin/black tests typings
    ./.venv/bin/isort tests typings
fi

# type check code
./.venv/bin/mypy tests typings

# lint
./.venv/bin/flake8 tests typings
