# Stubs for django.contrib.admin.actions (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from django.contrib.admin.options import ModelAdmin
from django.core.handlers.wsgi import WSGIRequest
from django.db.models.query import QuerySet
from django.template.response import TemplateResponse

def delete_selected(
    modeladmin: ModelAdmin, request: WSGIRequest, queryset: QuerySet
) -> TemplateResponse: ...
