# Stubs for django.contrib.admin.decorators (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

from typing import Callable

def register(*models: Any, site: Optional[Any] = ...) -> Callable: ...
