from typing import (
    Any,
    Iterator,
)


class AppConfig:
    def __init__(self, app_name: str, app_module: Any) -> None: ...
    def _path_from_module(self, module: Any) -> str: ...
    @classmethod
    def create(cls, entry: str) -> AppConfig: ...
    def get_model(self, model_name: str, require_ready: bool = ...) -> Any: ...
    def get_models(self, include_auto_created: bool = ..., include_swapped: bool = ...) -> Iterator[Any]: ...
    def import_models(self) -> None: ...
    def ready(self) -> None: ...