from django.apps.config import AppConfig
from django.db.migrations.state import AppConfigStub
from django.db.models.base import Model
from typing import (
    List,
    Optional,
    Tuple,
    Type,
    Union,
)


class Apps:
    def __init__(
        self,
        installed_apps: Union[Tuple, List[str], List[AppConfigStub]] = ...
    ) -> None: ...
    def check_apps_ready(self) -> None: ...
    def check_models_ready(self) -> None: ...
    def clear_cache(self) -> None: ...
    def do_pending_operations(self, model: Type[Model]) -> None: ...
    def get_app_config(self, app_label: str) -> AppConfig: ...
    def get_containing_app_config(self, object_name: str) -> Optional[AppConfig]: ...
    def get_model(
        self,
        app_label: str,
        model_name: None = ...,
        require_ready: bool = ...
    ) -> Type[Model]: ...