# Stubs for django.contrib.admin.templatetags.admin_static (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

register: Any

def static(path: str) -> str: ...
