# Stubs for django.contrib.admin.templatetags.admin_urls (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

from django.db.models.options import Options
from django.template.context import RequestContext
from django.utils.safestring import SafeText
from typing import Dict, Optional, Union
from uuid import UUID

register: Any

def admin_urlname(value: Options, arg: SafeText) -> str: ...
def admin_urlquote(value: Union[str, int, UUID]) -> Union[str, int, UUID]: ...
def add_preserved_filters(
    context: Union[Dict[str, Union[str, Options]], RequestContext],
    url: str,
    popup: bool = ...,
    to_field: Optional[str] = ...,
) -> str: ...
