# Stubs for django.contrib.admin.templatetags.base (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.template.library import InclusionNode
from typing import Any

from django.template.base import Parser, Token
from django.template.context import Context
from django.utils.safestring import SafeText
from typing import Callable

class InclusionAdminNode(InclusionNode):
    template_name: Any = ...
    def __init__(
        self,
        parser: Parser,
        token: Token,
        func: Callable,
        template_name: str,
        takes_context: bool = ...,
    ) -> None: ...
    def render(self, context: Context) -> SafeText: ...
