from datetime import (
    date,
    time,
)
from typing import Union


def format(value: Union[time, str, date], format_string: str) -> str: ...


def time_format(value: Union[date, time, str], format_string: str) -> str: ...


class DateFormat:
    def I(self) -> str: ...
    def L(self) -> bool: ...
    def M(self) -> str: ...
    def S(self) -> str: ...
    def U(self) -> int: ...
    def Y(self) -> int: ...
    def c(self) -> str: ...
    def d(self) -> str: ...
    def j(self) -> int: ...
    def m(self) -> str: ...
    def n(self) -> int: ...
    def o(self) -> int: ...
    def r(self) -> str: ...
    def t(self) -> str: ...
    def y(self) -> str: ...


class Formatter:
    def format(self, formatstr: str) -> str: ...


class TimeFormat:
    def A(self) -> str: ...
    def G(self) -> int: ...
    def H(self) -> str: ...
    def O(self) -> str: ...
    def P(self) -> str: ...
    def T(self) -> str: ...
    def Z(self) -> Union[str, int]: ...
    def __init__(self, obj: Union[time, date, str]) -> None: ...
    def a(self) -> str: ...
    def e(self) -> str: ...
    def f(self) -> Union[str, int]: ...
    def g(self) -> int: ...
    def h(self) -> str: ...
    def i(self) -> str: ...
    def s(self) -> str: ...
    def u(self) -> str: ...