from typing import Any

from django.db.models import Lookup, Transform
from django.db.models.lookups import Exact, PostgresOperatorLookup

from .search import SearchVectorExact

class DataContains(PostgresOperatorLookup[Any]): ...
class ContainedBy(PostgresOperatorLookup[Any]): ...
class Overlap(PostgresOperatorLookup[Any]): ...
class HasKey(PostgresOperatorLookup[Any]): ...
class HasKeys(PostgresOperatorLookup[Any]): ...
class HasAnyKeys(HasKeys): ...
class Unaccent(Transform): ...
class SearchLookup(SearchVectorExact): ...
class TrigramSimilar(PostgresOperatorLookup[Any]): ...
