from django.contrib.sessions.backends.base import SessionBase

class SessionStore(SessionBase):
    def exists(self, session_key: str | None = None) -> bool: ...
    async def aexists(self, session_key: str | None = None) -> bool: ...
