from django.core.handlers.wsgi import WSGIRequest
from django.core.paginator import Paginator
from django.db.models.query import QuerySet
from django.http.response import JsonResponse


class AutocompleteJsonView:
    def get(self, request: WSGIRequest, *args, **kwargs) -> JsonResponse: ...
    def get_paginator(self, *args, **kwargs) -> Paginator: ...
    def get_queryset(self) -> QuerySet: ...
    def has_perm(self, request: WSGIRequest, obj: None = ...) -> bool: ...