# Stubs for django.contrib.admin.views.decorators (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

from typing import Callable

def staff_member_required(
    view_func: None = ..., redirect_field_name: str = ..., login_url: str = ...
) -> Callable: ...
