from typing import Any, Dict, Iterator, List, Tuple, Union

from django.template.base import Template

class BaseEngine:
    name: Any = ...
    dirs: Any = ...
    app_dirs: Any = ...
    def __init__(self, params: Dict[str, Union[List[str], bool, str]]) -> None: ...
    @property
    def app_dirname(self) -> None: ...
    def from_string(self, template_code: Any) -> Template: ...
    def get_template(self, template_name: Any) -> None: ...
    def template_dirs(self) -> Tuple[str]: ...
    def iter_template_filenames(self, template_name: str) -> Iterator[str]: ...
