class RegisterLookupMixin:
    pass

class Q(object):
    def __init__(self, *args, **kwargs) -> None: ...
    def __or__(self, other: Q) -> Q: ...
    def __and__(self, other: Q) -> Q: ...
    def __invert__(self) -> Q: ...
