# Stubs for django.db.models.signals (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.dispatch import Signal
from typing import Any, Optional

from django.apps.registry import Apps
from django.contrib.sites.models import Site
from django.db.models.base import Model
from typing import Any, Callable, Optional, Type, Union

class_prepared: Any

class ModelSignal(Signal):
    def _lazy_method(
        self,
        method: Callable,
        apps: Optional[Apps],
        receiver: Callable,
        sender: Any,
        **kwargs: Any,
    ) -> Optional[bool]: ...
    def connect(
        self,
        receiver: Callable,
        sender: Optional[Union[Type[Site], Type[Model]]] = ...,
        weak: bool = ...,
        dispatch_uid: None = ...,
        apps: None = ...,
    ) -> None: ...
    def disconnect(
        self,
        receiver: Callable = ...,
        sender: Optional[Type[Model]] = ...,
        dispatch_uid: None = ...,
        apps: None = ...,
    ) -> bool: ...

pre_init: Any
post_init: Any
pre_save: Any
post_save: Any
pre_delete: Any
post_delete: Any
m2m_changed: Any
pre_migrate: Any
post_migrate: Any
