from typing import Any, Optional

from django.core.management.base import BaseCommand, CommandParser

UserModel: Any

class Command(BaseCommand):
    stderr: django.core.management.base.OutputWrapper
    stdout: django.core.management.base.OutputWrapper
    style: django.core.management.color.Style
    help: str = ...
    requires_migrations_checks: bool = ...
    requires_system_checks: bool = ...
    def add_arguments(self, parser: CommandParser) -> None: ...
    def handle(self, *args: Any, **options: Any) -> str: ...
