from django.db.migrations.migration import Migration
from django.db.migrations.operations.base import Operation
from typing import (
    Any,
    Set,
    Tuple,
    Type,
    Union,
)


class MigrationWriter:
    def __init__(self, migration: Migration) -> None: ...
    def as_string(self) -> str: ...
    @property
    def basedir(self) -> str: ...
    @property
    def filename(self) -> str: ...
    @property
    def path(self) -> str: ...
    @classmethod
    def serialize(cls, value: Any) -> Union[Tuple[str, Set[str]], Tuple[str, Set[Any]]]: ...


class OperationWriter:
    def __init__(self, operation: Operation, indentation: int = ...) -> None: ...
    def feed(self, line: str) -> None: ...
    def indent(self) -> None: ...
    def render(self) -> str: ...
    def serialize(self) -> Union[Tuple[str, Set[str]], Tuple[str, Set[Any]]]: ...
    def unindent(self) -> None: ...


class SettingsReference:
    def __init__(self, value: str, setting_name: str) -> None: ...
    @staticmethod
    def __new__(
        self: Type[SettingsReference],
        value: str,
        setting_name: str
    ) -> SettingsReference: ...