# Stubs for django.contrib.sites.apps (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .management import create_default_site
from django.apps import AppConfig
from typing import Any

class SitesConfig(AppConfig):
    name: str = ...
    verbose_name: Any = ...
    def ready(self) -> None: ...
