from django.http.request import HttpRequest
from typing import (
    Optional,
    Type,
)


def _simple_domain_name_validator(value: str): ...


def clear_site_cache(sender: Type[Site], **kwargs) -> None: ...


class Site:
    def __str__(self) -> str: ...


class SiteManager:
    def _get_site_by_id(self, site_id: int) -> Site: ...
    def _get_site_by_request(self, request: HttpRequest) -> Site: ...
    def clear_cache(self) -> None: ...
    def get_by_natural_key(self, domain: str) -> Site: ...
    def get_current(
        self,
        request: Optional[HttpRequest] = ...
    ) -> Site: ...