# Stubs for django.db.migrations.topological_sort (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from typing import Any, Iterator
def topological_sort_as_sets(dependency_graph: Any) -> Iterator[Any]: ...
def stable_topological_sort(l: Any, dependency_graph: Any) -> Any: ...
