from typing import Any, Optional

from django.utils.functional import SimpleLazyObject

COMPILED_REGEX_TYPE: Any

class RegexObject:
    pattern: str = ...
    flags: int = ...
    def __init__(self, obj: SimpleLazyObject) -> None: ...

def get_migration_name_timestamp() -> str: ...
