from django.core.handlers.wsgi import WSGIRequest


class StaticFilesHandler:
    def file_path(self, url: str) -> str: ...
    def get_response(self, request: WSGIRequest): ...
    def load_middleware(self) -> None: ...