from django.db.backends.mysql.base import DatabaseWrapper as MySQLDatabaseWrapper
from typing import Any

class DatabaseWrapper(MySQLDatabaseWrapper):
    SchemaEditorClass: Any = ...
    features_class: Any = ...
    introspection_class: Any = ...
    ops_class: Any = ...
