import os
from pathlib import Path

_PathCompatible = str | os.PathLike[str]

def safe_join(base: _PathCompatible, *paths: _PathCompatible) -> str: ...
def symlinks_supported() -> bool: ...
def to_path(value: Path | str) -> Path: ...
