from collections import OrderedDict
from typing import (Any, Callable, Dict, Iterator, List, Optional, Tuple, Type,
                    Union)
from unittest.case import TestCase

from django.db.models.base import Model
from django.urls.converters import IntConverter, StringConverter


class OrderedSet:
    dict: collections.OrderedDict = ...
    def __init__(
        self,
        iterable: Optional[
            Union[List[int], List[Tuple[str, str]], List[None], OrderedDict]
        ] = ...,
    ) -> None: ...
    def add(self, item: Union[TestCase, Type[Model]]) -> None: ...
    def remove(self, item: Any) -> None: ...
    def discard(self, item: Any) -> None: ...
    def __iter__(self): ...
    def __contains__(self, item: Any): ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...

class MultiValueDictKeyError(KeyError): ...

class MultiValueDict(dict):
    def __init__(self, key_to_list_mapping: Any = ...) -> None: ...
    def __getitem__(self, key: str) -> Optional[str]: ...
    def __setitem__(self, key: str, value: None) -> None: ...
    def __copy__(self): ...
    def __deepcopy__(self, memo: Any): ...
    def get(
        self, key: str, default: Optional[Union[str, int]] = ...
    ) -> Optional[Union[str, int]]: ...
    def getlist(self, key: Any, default: Optional[Any] = ...): ...
    def setlist(self, key: str, list_: List[Any]) -> None: ...
    def setdefault(self, key: Any, default: Optional[Any] = ...): ...
    def setlistdefault(
        self, key: str, default_list: None = ...
    ) -> List[str]: ...
    def appendlist(
        self,
        key: Union[Callable, str],
        value: Union[
            str,
            Tuple[
                List[Tuple[str, List[str]]],
                str,
                Dict[Any, Any],
                Dict[str, Union[IntConverter, StringConverter]],
            ],
        ],
    ) -> None: ...
    def items(self) -> Iterator[Tuple[str, str]]: ...
    def lists(self): ...
    def values(self) -> None: ...
    def copy(self): ...
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    def dict(self): ...

class ImmutableList(tuple):
    warning: str = ...
    def __new__(
        cls: Type[ImmutableList], *args: Any, warning: str = ..., **kwargs: Any
    ) -> ImmutableList: ...
    def complain(self, *wargs: Any, **kwargs: Any) -> None: ...
    __delitem__: Any = ...
    __delslice__: Any = ...
    __iadd__: Any = ...
    __imul__: Any = ...
    __setitem__: Any = ...
    __setslice__: Any = ...
    append: Any = ...
    extend: Any = ...
    insert: Any = ...
    pop: Any = ...
    remove: Any = ...
    sort: Any = ...
    reverse: Any = ...

class DictWrapper(dict):
    func: Callable = ...
    prefix: str = ...
    def __init__(self, data: Any, func: Any, prefix: Any) -> None: ...
    def __getitem__(self, key: str) -> int: ...
