from datetime import date as real_date
from datetime import datetime as real_datetime
from datetime import time as real_time
from typing import Union

class date(real_date): ...
class datetime(real_datetime): ...
class time(real_time): ...

def new_date(d: real_date) -> date: ...
def new_datetime(d: Union[real_date, real_datetime]) -> datetime: ...
def strftime(dt: Union[real_date, real_datetime], fmt: str) -> str: ...
