from datetime import date as real_date
from datetime import datetime as real_datetime
from datetime import time as real_time

class date(real_date):
    def strftime(self, fmt: str) -> str: ...

class datetime(real_datetime):
    def strftime(self, fmt: str) -> str: ...
    @classmethod
    def combine(cls, date: real_date, time: real_time) -> datetime: ...  # type: ignore[override]

def new_date(d: real_date) -> date: ...
def new_datetime(d: real_date | real_datetime) -> datetime: ...
def strftime(dt: real_date | real_datetime, fmt: str) -> str: ...
