# Stubs for django.utils.deconstruct (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

from django.contrib.postgres.validators import KeysValidator
from django.core.validators import RegexValidator
from typing import Type, Union
def deconstructible(*args: Any, path: Optional[Any] = ...) -> Type[Union[KeysValidator, RegexValidator]]: ...
