# Stubs for django.utils.ipv6 (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def clean_ipv6_address(ip_str: Any, unpack_ipv4: bool = ..., error_message: Any = ...): ...
def is_valid_ipv6_address(ip_str: str) -> bool: ...
