# Stubs for django.utils.lorem_ipsum (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

COMMON_P: str
WORDS: Any
COMMON_WORDS: Any

def sentence() -> str: ...
def paragraph() -> str: ...
def paragraphs(count: Any, common: bool = ...): ...
def words(count: int, common: bool = ...) -> str: ...
