from typing import Any, Iterator, List, Optional, Tuple, Type, Union

ESCAPE_MAPPINGS: Any

class Choice(list): ...
class Group(list): ...
class NonCapture(list): ...

def normalize(pattern: str) -> List[Tuple[str, List[str]]]: ...
def next_char(input_iter: Any) -> None: ...
def walk_to_end(ch: str, input_iter: Iterator[Any]) -> None: ...
def get_quantifier(
    ch: str, input_iter: Iterator[Any]
) -> Tuple[int, Optional[str]]: ...
def contains(
    source: Union[str, NonCapture, Group], inst: Type[Group]
) -> bool: ...
def flatten_result(
    source: Optional[
        Union[
            List[Union[str, NonCapture]],
            List[Union[str, Group, Choice]],
            NonCapture,
            Group,
        ]
    ]
) -> Tuple[List[str], List[List[str]]]: ...
