# Stubs for django.utils.safestring (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from django.forms.boundfield import BoundField
from typing import Callable, Union

class SafeData:
    def __html__(self) -> SafeText: ...

class SafeBytes(bytes, SafeData):
    def __add__(self, rhs: Any): ...

class SafeText(str, SafeData):
    def __add__(self, rhs: str) -> str: ...
    def __str__(self) -> SafeText: ...

SafeString = SafeText

def _safety_decorator(safety_marker: Callable, func: Callable) -> Callable: ...
def mark_safe(
    s: Union[str, BoundField, Callable]
) -> Union[SafeText, BoundField, Callable]: ...
