# Stubs for django.utils.termcolors (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from typing import Callable, Dict, Optional, Tuple, Union

color_names: Any
foreground: Any
background: Any
RESET: str
opt_dict: Any

def colorize(text: str = ..., opts: Union[str, Tuple] = ..., **kwargs: Any) -> str: ...
def make_style(opts: Tuple = ..., **kwargs: Any) -> Callable: ...

NOCOLOR_PALETTE: str
DARK_PALETTE: str
LIGHT_PALETTE: str
PALETTES: Any
DEFAULT_PALETTE = DARK_PALETTE

def parse_color_setting(
    config_string: str
) -> Optional[
    Union[Dict[str, Dict[str, Union[str, Tuple[str]]]], Dict[str, Dict[str, str]]]
]: ...
