from typing import Any, Dict, Optional, Tuple


class Node:
    default: str = ...
    children: Union[
        List[
            Union[
                django.db.models.lookups.BuiltinLookup,
                django.db.models.sql.where.WhereNode,
            ]
        ],
        List[Tuple[str, int]],
    ] = ...
    connector: str = ...
    negated: bool = ...
    def __init__(
        self,
        children: Any = ...,
        connector: Optional[str] = ...,
        negated: bool = ...,
    ) -> None: ...
    def __deepcopy__(self, memodict: Dict[Any, Any]) -> Node: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, other: Tuple[str, int]) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self): ...
    def add(self, data: Any, conn_type: str, squash: bool = ...) -> Any: ...
    def negate(self) -> None: ...
