from typing import Optional, Tuple

PY36: bool
PY37: bool
PY38: bool
PY39: bool

_VT = Tuple[int, int, int, str, int]

def get_version(version: Optional[_VT] = ...) -> str: ...
def get_main_version(version: _VT = ...) -> str: ...
def get_complete_version(version: Optional[_VT] = ...) -> _VT: ...
def get_docs_version(version: Optional[_VT] = ...) -> str: ...
def get_git_changeset() -> Optional[str]: ...
def get_version_tuple(version: str) -> Tuple[int, int, int]: ...
