# Stubs for django.utils.xmlutils (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from xml.sax.saxutils import XMLGenerator

from typing import Dict, Optional

class UnserializableContentError(ValueError): ...

class SimplerXMLGenerator(XMLGenerator):
    def addQuickElement(
        self,
        name: str,
        contents: Optional[str] = ...,
        attrs: Optional[Dict[str, str]] = ...,
    ) -> None: ...
    def characters(self, content: str) -> None: ...
    def startElement(self, name: str, attrs: Dict[str, str]) -> None: ...
