# Stubs for django.conf.urls (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.urls import include as include
from typing import Any, Optional

from django.urls.resolvers import URLPattern, URLResolver
from typing import Any, Optional, Union

handler400: Any
handler403: Any
handler404: Any
handler500: Any

def url(
    regex: str, view: Any, kwargs: Any = ..., name: Optional[str] = ...
) -> Union[URLPattern, URLResolver]: ...
