# Stubs for django.conf.urls.static (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from django.urls.resolvers import URLPattern
from typing import Callable, List
def static(prefix: str, view: Callable = ..., **kwargs: Any) -> List[URLPattern]: ...
