# Stubs for django.core.mail.utils (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class CachedDnsName:
    def __str__(self) -> str: ...
    _fqdn: Any = ...
    def get_fqdn(self) -> str: ...

DNS_NAME: Any
