# Stubs for django.middleware.clickjacking (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.deprecation import MiddlewareMixin
from typing import Any

from django.http.request import HttpRequest
from django.http.response import HttpResponse

class XFrameOptionsMiddleware(MiddlewareMixin):
    def process_response(
        self, request: HttpRequest, response: HttpResponse
    ) -> HttpResponse: ...
    def get_xframe_options_value(
        self, request: HttpRequest, response: HttpResponse
    ) -> str: ...
