# Stubs for django.middleware.gzip (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.deprecation import MiddlewareMixin
from typing import Any

from django.core.handlers.wsgi import WSGIRequest
from django.http.response import HttpResponseBase
re_accepts_gzip: Any

class GZipMiddleware(MiddlewareMixin):
    def process_response(self, request: WSGIRequest, response: HttpResponseBase) -> HttpResponseBase: ...
