# Stubs for django.middleware.http (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.deprecation import MiddlewareMixin
from typing import Any

from django.core.handlers.wsgi import WSGIRequest
from django.http.response import HttpResponse

class ConditionalGetMiddleware(MiddlewareMixin):
    def process_response(
        self, request: WSGIRequest, response: HttpResponse
    ) -> HttpResponse: ...
    def needs_etag(self, response: HttpResponse) -> bool: ...
