# Stubs for django.middleware.locale (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.deprecation import MiddlewareMixin
from typing import Any

from django.core.handlers.wsgi import WSGIRequest
from django.http.response import HttpResponse

class LocaleMiddleware(MiddlewareMixin):
    response_redirect_class: Any = ...
    def process_request(self, request: WSGIRequest) -> None: ...
    def process_response(
        self, request: WSGIRequest, response: HttpResponse
    ) -> HttpResponse: ...
