# Stubs for django.core.management.sql (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from django.core.management.color import Style
from django.db.backends.sqlite3.base import DatabaseWrapper
from typing import List

def sql_flush(
    style: Style,
    connection: DatabaseWrapper,
    only_django: bool = ...,
    reset_sequences: bool = ...,
    allow_cascade: bool = ...,
) -> List[str]: ...
def emit_pre_migrate_signal(
    verbosity: int, interactive: bool, db: str, **kwargs: Any
) -> None: ...
def emit_post_migrate_signal(
    verbosity: int, interactive: bool, db: str, **kwargs: Any
) -> None: ...
