from typing import (
    Any,
    Dict,
    Optional,
)


class SessionStore:
    def __init__(self, session_key: None = ...) -> None: ...
    @property
    def cache_key(self) -> str: ...
    def create(self) -> None: ...
    def delete(self, session_key: Optional[str] = ...) -> None: ...
    def exists(self, session_key: Optional[str]) -> bool: ...
    def load(self) -> Dict[Any, Any]: ...
    def save(self, must_create: bool = ...) -> None: ...