from typing import (
    Dict,
    Optional,
)


class SessionStore:
    def __init__(self, session_key: Optional[str] = ...) -> None: ...
    @classmethod
    def _get_storage_path(cls) -> str: ...
    def _key_to_file(self, session_key: Optional[str] = ...) -> str: ...
    @classmethod
    def clear_expired(cls) -> None: ...
    def create(self) -> None: ...
    def delete(self, session_key: Optional[str] = ...) -> None: ...
    def exists(self, session_key: Optional[str]) -> bool: ...
    def load(self) -> Dict[str, str]: ...
    def save(self, must_create: bool = ...) -> None: ...