from datetime import datetime
from typing import (
    Dict,
    Optional,
    Union,
)


class SessionStore:
    def _get_session_key(self) -> str: ...
    def delete(self, session_key: Optional[str] = ...) -> None: ...
    def exists(self, session_key: str = ...) -> bool: ...
    def load(self) -> Dict[str, Union[str, datetime]]: ...
    def save(self, must_create: bool = ...) -> None: ...