from django.core.handlers.wsgi import WSGIHandler
from django.core.management.base import CommandParser


class Command:
    def add_arguments(self, parser: CommandParser) -> None: ...
    def execute(self, *args, **options) -> None: ...
    def get_handler(self, *args, **options) -> WSGIHandler: ...
    def handle(self, *args, **options) -> None: ...