from typing import IO, Any

from django.contrib.gis.geos.geometry import GEOSGeometry

def fromfile(file_h: str | IO) -> GEOSGeometry: ...
def fromstr(string: str, **kwargs: Any) -> GEOSGeometry: ...
