from typing import Any, Protocol

from django.contrib.gis.geos.geometry import GEOSGeometry

class _Reader(Protocol):
    def read(self) -> str | bytes: ...

def fromfile(file_h: str | _Reader) -> GEOSGeometry: ...
def fromstr(string: str, **kwargs: Any) -> GEOSGeometry: ...
