from typing import Any, BinaryIO, TextIO

from django.contrib.gis.geos.geometry import GEOSGeometry

def fromfile(file_h: str | TextIO | BinaryIO) -> GEOSGeometry: ...
def fromstr(string: str, **kwargs: Any) -> GEOSGeometry: ...
