from collections.abc import Iterator
from typing import Any

from django.contrib.gis.geos.geometry import GEOSGeometry as GEOSGeometry

class Point(GEOSGeometry):
    has_cs: bool
    def __init__(
        self, x: Any | None = ..., y: Any | None = ..., z: Any | None = ..., srid: Any | None = ...
    ) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    @property
    def x(self) -> Any: ...
    @x.setter
    def x(self, value: Any) -> None: ...
    @property
    def y(self) -> Any: ...
    @y.setter
    def y(self, value: Any) -> None: ...
    @property
    def z(self) -> Any: ...
    @z.setter
    def z(self, value: Any) -> None: ...
    @property
    def tuple(self) -> Any: ...
    @tuple.setter
    def tuple(self, tup: Any) -> None: ...
    coords: Any
