from typing import Any, Iterator

from django.contrib.gis.geos.geometry import GEOSGeometry as GEOSGeometry

class Polygon(GEOSGeometry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    @classmethod
    def from_bbox(cls, bbox: Any) -> Any: ...
    @property
    def num_interior_rings(self) -> Any: ...
    exterior_ring: Any
    shell: Any
    @property
    def tuple(self) -> Any: ...
    coords: Any
    @property
    def kml(self) -> Any: ...
