from typing import Any, Optional

def arg_byref(args: Any, offset: int = ...): ...
def ptr_byref(args: Any, offset: int = ...): ...
def check_const_string(result: Any, func: Any, cargs: Any, offset: Optional[Any] = ..., cpl: bool = ...): ...
def check_string(result: Any, func: Any, cargs: Any, offset: int = ..., str_result: bool = ...): ...
def check_envelope(result: Any, func: Any, cargs: Any, offset: int = ...): ...
def check_geom(result: Any, func: Any, cargs: Any): ...
def check_geom_offset(result: Any, func: Any, cargs: Any, offset: int = ...): ...
def check_srs(result: Any, func: Any, cargs: Any): ...
def check_arg_errcode(result: Any, func: Any, cargs: Any, cpl: bool = ...): ...
def check_errcode(result: Any, func: Any, cargs: Any, cpl: bool = ...) -> None: ...
def check_pointer(result: Any, func: Any, cargs: Any): ...
def check_str_arg(result: Any, func: Any, cargs: Any): ...
