from contextlib import contextmanager
from types import TracebackType
from typing import Any, Callable, Dict, Iterable, Iterator, List, Type, TypeVar

from django.http.request import HttpRequest
from django.template.base import Node, Origin, Template
from django.template.defaulttags import IfChangedNode
from django.template.loader_tags import IncludeNode

_ContextKeys = int | str | Node
_ContextValues = Dict[str, Any] | "Context"
_ContextCopy = TypeVar("_ContextCopy", bound="BaseContext")

class ContextPopException(Exception): ...

class ContextDict(dict):
    context: BaseContext = ...
    def __init__(self, context: BaseContext, *args: Any, **kwargs: Any) -> None: ...
    def __enter__(self) -> ContextDict: ...
    def __exit__(
        self,
        exc_type: Type[BaseException] | None,
        exc_value: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...

class BaseContext(Iterable[Any]):
    def __init__(self, dict_: Any = ...) -> None: ...
    def __copy__(self: _ContextCopy) -> _ContextCopy: ...
    def __iter__(self) -> Iterator[Any]: ...
    def push(self, *args: Any, **kwargs: Any) -> ContextDict: ...
    def pop(self) -> ContextDict: ...
    def __setitem__(self, key: _ContextKeys, value: Any) -> None: ...
    def set_upward(self, key: _ContextKeys, value: int | str) -> None: ...
    def __getitem__(self, key: _ContextKeys) -> Any: ...
    def __delitem__(self, key: _ContextKeys) -> None: ...
    def __contains__(self, key: _ContextKeys) -> bool: ...
    def get(self, key: _ContextKeys, otherwise: Any | None = ...) -> Any | None: ...
    def setdefault(self, key: _ContextKeys, default: List[Origin] | int | None = ...) -> List[Origin] | int | None: ...
    def new(self, values: _ContextValues | None = ...) -> Context: ...
    def flatten(self) -> Dict[_ContextKeys, Dict[_ContextKeys, Type[Any] | str] | int | str | None]: ...

class Context(BaseContext):
    dicts: Any
    autoescape: bool = ...
    use_l10n: bool | None = ...
    use_tz: bool | None = ...
    template_name: str | None = ...
    render_context: RenderContext = ...
    template: Template | None = ...
    def __init__(
        self, dict_: Any = ..., autoescape: bool = ..., use_l10n: bool | None = ..., use_tz: bool | None = ...
    ) -> None: ...
    @contextmanager
    def bind_template(self, template: Template) -> Iterator[None]: ...
    def update(self, other_dict: Dict[str, Any] | Context) -> ContextDict: ...

class RenderContext(BaseContext):
    dicts: List[Dict[IncludeNode | str, str]]
    template: Template | None = ...
    @contextmanager
    def push_state(self, template: Template, isolated_context: bool = ...) -> Iterator[None]: ...

class RequestContext(Context):
    autoescape: bool
    dicts: List[Dict[str, str]]
    render_context: RenderContext
    template_name: str | None
    use_l10n: bool | None
    use_tz: bool | None
    request: HttpRequest = ...
    def __init__(
        self,
        request: HttpRequest,
        dict_: Dict[str, Any] | None = ...,
        processors: List[Callable] | None = ...,
        use_l10n: bool | None = ...,
        use_tz: bool | None = ...,
        autoescape: bool = ...,
    ) -> None: ...
    template: Template | None = ...
    @contextmanager
    def bind_template(self, template: Template) -> Iterator[None]: ...
    def new(self, values: _ContextValues | None = ...) -> RequestContext: ...

def make_context(context: Any, request: HttpRequest | None = ..., **kwargs: Any) -> Context: ...
