from typing import Callable, Dict, List, Tuple, TypeVar

from django.http.request import HttpRequest
from django.utils.functional import SimpleLazyObject

_R = TypeVar("_R", bound=HttpRequest)

def csrf(request: HttpRequest) -> Dict[str, SimpleLazyObject]: ...
def debug(request: HttpRequest) -> Dict[str, Callable | bool]: ...
def i18n(request: HttpRequest) -> Dict[str, List[Tuple[str, str]] | bool | str]: ...
def tz(request: HttpRequest) -> Dict[str, str]: ...
def static(request: HttpRequest) -> Dict[str, str]: ...
def media(request: HttpRequest) -> Dict[str, str]: ...
def request(request: _R) -> Dict[str, _R]: ...
