from collections import namedtuple
from datetime import date
from typing import Any, Dict, List, Optional, Tuple, Union

from django.template.base import FilterExpression, NodeList, Parser, Token
from django.template.context import Context, RequestContext
from django.template.library import Library
from django.utils.safestring import SafeText

from .base import (BLOCK_TAG_END, BLOCK_TAG_START, COMMENT_TAG_END,
                   COMMENT_TAG_START, FILTER_SEPARATOR, SINGLE_BRACE_END,
                   SINGLE_BRACE_START, VARIABLE_ATTRIBUTE_SEPARATOR,
                   VARIABLE_TAG_END, VARIABLE_TAG_START, Context, Node,
                   NodeList, TemplateSyntaxError, VariableDoesNotExist,
                   kwarg_re, render_value_in_context, token_kwargs)
from .defaultfilters import date
from .library import Library
from .smartif import IfParser, Literal

register: Any

class AutoEscapeControlNode(Node):
    nodelist: django.template.base.NodeList
    origin: django.template.base.Origin
    setting: bool
    token: django.template.base.Token
    def __init__(self, setting: bool, nodelist: NodeList) -> None: ...
    def render(self, context: Context) -> SafeText: ...

class CommentNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    def render(self, context: Context) -> str: ...

class CsrfTokenNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    def render(self, context: RequestContext) -> SafeText: ...

class CycleNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    cyclevars: List[django.template.base.FilterExpression] = ...
    variable_name: Optional[str] = ...
    silent: bool = ...
    def __init__(
        self,
        cyclevars: List[FilterExpression],
        variable_name: Optional[str] = ...,
        silent: bool = ...,
    ) -> None: ...
    def render(self, context: Context) -> str: ...
    def reset(self, context: Context) -> None: ...

class DebugNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    def render(self, context: Context) -> str: ...

class FilterNode(Node):
    filter_expr: django.template.base.FilterExpression
    nodelist: django.template.base.NodeList
    origin: django.template.base.Origin
    token: django.template.base.Token
    def __init__(
        self, filter_expr: FilterExpression, nodelist: NodeList
    ) -> None: ...
    def render(self, context: Context) -> Any: ...

class FirstOfNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    vars: List[django.template.base.FilterExpression] = ...
    asvar: Optional[str] = ...
    def __init__(
        self, variables: List[FilterExpression], asvar: Optional[str] = ...
    ) -> None: ...
    def render(self, context: Context) -> str: ...

class ForNode(Node):
    loopvars: Union[str, List[str]]
    origin: django.template.base.Origin
    sequence: Union[str, django.template.base.FilterExpression]
    token: django.template.base.Token
    child_nodelists: Any = ...
    is_reversed: bool = ...
    nodelist_loop: Union[django.template.base.NodeList, List[str]] = ...
    nodelist_empty: Union[django.template.base.NodeList, List[str]] = ...
    def __init__(
        self,
        loopvars: Union[str, List[str]],
        sequence: Union[str, FilterExpression],
        is_reversed: bool,
        nodelist_loop: Union[NodeList, List[str]],
        nodelist_empty: Optional[Union[NodeList, List[str]]] = ...,
    ) -> None: ...
    def render(self, context: Context) -> SafeText: ...

class IfChangedNode(Node):
    nodelist_false: django.template.base.NodeList
    nodelist_true: django.template.base.NodeList
    origin: django.template.base.Origin
    token: django.template.base.Token
    child_nodelists: Any = ...
    def __init__(
        self, nodelist_true: NodeList, nodelist_false: NodeList, *varlist: Any
    ) -> None: ...
    def render(self, context: Context) -> str: ...

class IfEqualNode(Node):
    nodelist_false: Union[django.template.base.NodeList, List[Any]]
    nodelist_true: Union[django.template.base.NodeList, List[Any]]
    origin: django.template.base.Origin
    token: django.template.base.Token
    var1: Union[str, django.template.base.FilterExpression]
    var2: Union[str, django.template.base.FilterExpression]
    child_nodelists: Any = ...
    negate: bool = ...
    def __init__(
        self,
        var1: Union[str, FilterExpression],
        var2: Union[str, FilterExpression],
        nodelist_true: Union[NodeList, List[Any]],
        nodelist_false: Union[NodeList, List[Any]],
        negate: bool,
    ) -> None: ...
    def render(self, context: Context) -> SafeText: ...

class IfNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    conditions_nodelists: Union[
        List[
            Tuple[
                django.template.defaulttags.TemplateLiteral,
                django.template.base.NodeList,
            ]
        ],
        List[
            Tuple[django.template.base.NodeList, django.template.base.NodeList]
        ],
    ] = ...
    def __init__(
        self,
        conditions_nodelists: Union[
            List[Tuple[TemplateLiteral, NodeList]],
            List[Tuple[NodeList, NodeList]],
        ],
    ) -> None: ...
    def __iter__(self) -> None: ...
    @property
    def nodelist(self) -> NodeList: ...
    def render(self, context: Context) -> str: ...

class LoremNode(Node):
    common: bool
    count: django.template.base.FilterExpression
    method: str
    origin: django.template.base.Origin
    token: django.template.base.Token
    def __init__(
        self, count: FilterExpression, method: str, common: bool
    ) -> None: ...
    def render(self, context: Context) -> str: ...

GroupedResult = namedtuple("GroupedResult", ["grouper", "list"])

class RegroupNode(Node):
    expression: django.template.base.FilterExpression
    origin: django.template.base.Origin
    target: django.template.base.FilterExpression
    token: django.template.base.Token
    var_name: str = ...
    def __init__(
        self,
        target: FilterExpression,
        expression: FilterExpression,
        var_name: str,
    ) -> None: ...
    def resolve_expression(
        self, obj: Dict[str, Union[str, int, List[str], date]], context: Context
    ) -> Union[str, int]: ...
    def render(self, context: Context) -> str: ...

class LoadNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    def render(self, context: Context) -> str: ...

class NowNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    format_string: str = ...
    asvar: Optional[str] = ...
    def __init__(
        self, format_string: str, asvar: Optional[str] = ...
    ) -> None: ...
    def render(self, context: Context) -> str: ...

class ResetCycleNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    node: django.template.defaulttags.CycleNode = ...
    def __init__(self, node: CycleNode) -> None: ...
    def render(self, context: Context) -> str: ...

class SpacelessNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    nodelist: django.template.base.NodeList = ...
    def __init__(self, nodelist: NodeList) -> None: ...
    def render(self, context: Context) -> str: ...

class TemplateTagNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    mapping: Any = ...
    tagtype: str = ...
    def __init__(self, tagtype: str) -> None: ...
    def render(self, context: Context) -> str: ...

class URLNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    view_name: django.template.base.FilterExpression = ...
    args: List[django.template.base.FilterExpression] = ...
    kwargs: Dict[str, django.template.base.FilterExpression] = ...
    asvar: Optional[str] = ...
    def __init__(
        self,
        view_name: FilterExpression,
        args: List[FilterExpression],
        kwargs: Dict[str, FilterExpression],
        asvar: Optional[str],
    ) -> None: ...
    def render(self, context: Context) -> str: ...

class VerbatimNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    content: django.utils.safestring.SafeText = ...
    def __init__(self, content: SafeText) -> None: ...
    def render(self, context: Context) -> SafeText: ...

class WidthRatioNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    val_expr: django.template.base.FilterExpression = ...
    max_expr: django.template.base.FilterExpression = ...
    max_width: django.template.base.FilterExpression = ...
    asvar: Optional[str] = ...
    def __init__(
        self,
        val_expr: FilterExpression,
        max_expr: FilterExpression,
        max_width: FilterExpression,
        asvar: Optional[str] = ...,
    ) -> None: ...
    def render(self, context: Context) -> str: ...

class WithNode(Node):
    origin: django.template.base.Origin
    token: django.template.base.Token
    nodelist: Union[django.template.base.NodeList, List[Any]] = ...
    extra_context: Dict[
        str, Union[django.template.base.FilterExpression, str]
    ] = ...
    def __init__(
        self,
        var: Optional[str],
        name: Optional[str],
        nodelist: Union[NodeList, List[Any]],
        extra_context: Optional[Dict[str, FilterExpression]] = ...,
    ) -> None: ...
    def render(self, context: Context) -> Any: ...

def autoescape(parser: Parser, token: Token) -> AutoEscapeControlNode: ...
def comment(parser: Parser, token: Token) -> CommentNode: ...
def cycle(parser: Parser, token: Token) -> CycleNode: ...
def csrf_token(parser: Parser, token: Token) -> CsrfTokenNode: ...
def debug(parser: Parser, token: Token) -> DebugNode: ...
def do_filter(parser: Parser, token: Token) -> FilterNode: ...
def firstof(parser: Parser, token: Token) -> FirstOfNode: ...
def do_for(parser: Parser, token: Token) -> ForNode: ...
def do_ifequal(parser: Parser, token: Token, negate: bool) -> IfEqualNode: ...
def ifequal(parser: Parser, token: Token) -> IfEqualNode: ...
def ifnotequal(parser: Parser, token: Token) -> IfEqualNode: ...

class TemplateLiteral(Literal):
    value: django.template.base.FilterExpression = ...
    text: str = ...
    def __init__(self, value: FilterExpression, text: str) -> None: ...
    def display(self) -> str: ...
    def eval(self, context: Context) -> Any: ...

class TemplateIfParser(IfParser):
    current_token: django.template.defaulttags.TemplateLiteral
    pos: int
    tokens: List[django.template.defaulttags.TemplateLiteral]
    error_class: Any = ...
    template_parser: django.template.base.Parser = ...
    def __init__(self, parser: Parser, *args: Any, **kwargs: Any) -> None: ...
    def create_var(self, value: str) -> TemplateLiteral: ...

def do_if(parser: Parser, token: Token) -> IfNode: ...
def ifchanged(parser: Parser, token: Token) -> IfChangedNode: ...
def find_library(parser: Parser, name: str) -> Library: ...
def load_from_library(
    library: Library, label: str, names: List[str]
) -> Library: ...
def load(parser: Parser, token: Token) -> LoadNode: ...
def lorem(parser: Parser, token: Token) -> LoremNode: ...
def now(parser: Parser, token: Token) -> NowNode: ...
def regroup(parser: Parser, token: Token) -> RegroupNode: ...
def resetcycle(parser: Parser, token: Token) -> ResetCycleNode: ...
def spaceless(parser: Parser, token: Token) -> SpacelessNode: ...
def templatetag(parser: Parser, token: Token) -> TemplateTagNode: ...
def url(parser: Parser, token: Token) -> URLNode: ...
def verbatim(parser: Parser, token: Token) -> VerbatimNode: ...
def widthratio(parser: Parser, token: Token) -> WidthRatioNode: ...
def do_with(parser: Parser, token: Token) -> WithNode: ...
