from datetime import date, time, timedelta
from decimal import Decimal
from typing import Any, Callable, Dict, Iterator, List, Optional, Tuple, Union

from django.utils.safestring import SafeText

from .base import Variable, VariableDoesNotExist
from .library import Library

register: Any

def stringfilter(func: Callable) -> Callable: ...
def addslashes(value: str) -> str: ...
def capfirst(value: str) -> str: ...
def escapejs_filter(value: str) -> SafeText: ...
def json_script(value: Dict[str, str], element_id: SafeText) -> SafeText: ...
def floatformat(
    text: Optional[Union[Decimal, float, str]], arg: Union[str, int] = ...
) -> str: ...
def iriencode(value: str) -> str: ...
def linenumbers(value: str, autoescape: bool = ...) -> SafeText: ...
def lower(value: str) -> str: ...
def make_list(value: str) -> List[str]: ...
def slugify(value: str) -> SafeText: ...
def stringformat(value: Any, arg: str) -> str: ...
def title(value: str) -> str: ...
def truncatechars(value: str, arg: Union[SafeText, int]) -> str: ...
def truncatechars_html(value: str, arg: Union[str, int]) -> str: ...
def truncatewords(value: str, arg: Union[str, int]) -> str: ...
def truncatewords_html(value: str, arg: Union[str, int]) -> str: ...
def upper(value: str) -> str: ...
def urlencode(value: str, safe: Optional[SafeText] = ...) -> str: ...
def urlize(value: str, autoescape: bool = ...) -> SafeText: ...
def urlizetrunc(
    value: str, limit: Union[SafeText, int], autoescape: bool = ...
) -> SafeText: ...
def wordcount(value: str) -> int: ...
def wordwrap(value: str, arg: Union[SafeText, int]) -> str: ...
def ljust(value: str, arg: Union[SafeText, int]) -> str: ...
def rjust(value: str, arg: Union[SafeText, int]) -> str: ...
def center(value: str, arg: Union[SafeText, int]) -> str: ...
def cut(value: str, arg: str) -> str: ...
def escape_filter(value: str) -> SafeText: ...
def force_escape(value: str) -> SafeText: ...
def linebreaks_filter(value: str, autoescape: bool = ...) -> SafeText: ...
def linebreaksbr(value: str, autoescape: bool = ...) -> SafeText: ...
def safe(value: str) -> SafeText: ...
def safeseq(value: List[str]) -> List[SafeText]: ...
def striptags(value: str) -> str: ...
def dictsort(
    value: Any, arg: Union[str, int]
) -> Union[
    List[Tuple[str, str]],
    List[Dict[str, Union[int, str]]],
    str,
    List[Dict[str, Dict[str, Union[int, str]]]],
]: ...
def dictsortreversed(
    value: Any, arg: Union[str, int]
) -> Union[str, List[Tuple[str, str]], List[Dict[str, Union[int, str]]]]: ...
def first(value: Union[str, List[int], List[str]]) -> Union[str, int]: ...
def join(value: Any, arg: str, autoescape: bool = ...) -> Any: ...
def last(value: List[str]) -> str: ...
def length(value: Any) -> int: ...
def length_is(value: Any, arg: Union[SafeText, int]) -> Union[bool, str]: ...
def random(value: List[str]) -> str: ...
def slice_filter(value: Any, arg: str) -> Any: ...
def unordered_list(
    value: Union[
        List[Union[List[str], str]],
        List[Union[str, List[SafeText]]],
        Iterator[Any],
        List[Union[str, List[Union[List[str], str]]]],
        List[Union[str, List[Union[str, List[Union[List[str], str]]]]]],
    ],
    autoescape: bool = ...,
) -> SafeText: ...
def add(
    value: Union[List[int], int, str, date, Tuple[int, int]],
    arg: Union[List[int], int, timedelta, str, Tuple[int, int]],
) -> Union[List[int], int, str, date, Tuple[int, int, int, int]]: ...
def get_digit(value: Union[str, int], arg: int) -> Union[str, int]: ...
def date(
    value: Optional[Union[time, str, date]], arg: Optional[str] = ...
) -> str: ...
def time(
    value: Optional[Union[time, str, date]], arg: Optional[str] = ...
) -> str: ...
def timesince_filter(
    value: Optional[date], arg: Optional[date] = ...
) -> str: ...
def timeuntil_filter(
    value: Optional[date], arg: Optional[date] = ...
) -> str: ...
def default(
    value: Optional[Union[str, int]], arg: Union[str, int]
) -> Union[str, int]: ...
def default_if_none(
    value: Optional[str], arg: Union[str, int]
) -> Union[str, int]: ...
def divisibleby(value: int, arg: int) -> bool: ...
def yesno(
    value: Optional[int], arg: Optional[str] = ...
) -> Optional[Union[str, bool]]: ...
def filesizeformat(bytes_: Union[str, complex, int]) -> str: ...
def pluralize(value: Any, arg: str = ...) -> str: ...
def phone2numeric_filter(value: str) -> str: ...
def pprint(value: Any) -> str: ...
