# Stubs for django.template.exceptions (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

from django.template.backends.base import BaseEngine
from django.template.base import Origin
from typing import List, Optional, Tuple, Union

class TemplateDoesNotExist(Exception):
    backend: Any = ...
    tried: Any = ...
    chain: Any = ...
    def __init__(
        self,
        msg: Union[str, Origin],
        tried: Optional[List[Tuple[Origin, str]]] = ...,
        backend: Optional[BaseEngine] = ...,
        chain: Optional[List[TemplateDoesNotExist]] = ...,
    ) -> None: ...

class TemplateSyntaxError(Exception): ...
