# Stubs for django.contrib.messages.storage.fallback (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.contrib.messages.storage.base import BaseStorage
from typing import Any

from django.contrib.messages.storage.base import Message
from django.http.response import HttpResponse
from typing import Any, List, Tuple, Union

class FallbackStorage(BaseStorage):
    storage_classes: Any = ...
    storages: Any = ...
    _used_storages: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def _get(
        self, *args: Any, **kwargs: Any
    ) -> Union[
        Tuple[List[Any], bool], Tuple[List[str], bool], Tuple[List[Message], bool]
    ]: ...
    def _store(
        self, messages: List[Message], response: HttpResponse, *args: Any, **kwargs: Any
    ) -> List[Any]: ...
