# Stubs for django.contrib.messages.storage.session (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.contrib.messages.storage.base import BaseStorage
from typing import Any

from django.contrib.messages.storage.base import Message
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from typing import Any, List, Optional, Tuple, Union

class SessionStorage(BaseStorage):
    session_key: str = ...
    def __init__(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None: ...
    def _get(
        self, *args: Any, **kwargs: Any
    ) -> Union[Tuple[None, bool], Tuple[List[str], bool], Tuple[List[Message], bool]]: ...
    def _store(
        self, messages: List[Message], response: HttpResponse, *args: Any, **kwargs: Any
    ) -> List[Any]: ...
    def serialize_messages(self, messages: Union[List[Message], List[str]]) -> str: ...
    def deserialize_messages(
        self, data: Optional[str]
    ) -> Optional[Union[List[Message], List[str]]]: ...
