# Stubs for django.core.wsgi (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.core.handlers.wsgi import WSGIHandler

def get_wsgi_application() -> WSGIHandler: ...
