# Stubs for django.core.checks.security.csrf (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from django.core.checks.messages import Warning
from typing import List

W003: Any
W016: Any

def _csrf_middleware() -> bool: ...
def check_csrf_middleware(app_configs: None, **kwargs: Any) -> List[Warning]: ...
def check_csrf_cookie_secure(app_configs: Any, **kwargs: Any): ...
