# Stubs for django.core.checks.security.sessions (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from typing import Any, List
def add_session_cookie_message(message: Any): ...

W010: Any
W011: Any
W012: Any

def add_httponly_message(message: Any): ...

W013: Any
W014: Any
W015: Any

def check_session_cookie_secure(app_configs: None, **kwargs: Any) -> List[Any]: ...
def check_session_cookie_httponly(app_configs: Any, **kwargs: Any): ...
def _session_middleware() -> bool: ...
def _session_app() -> bool: ...
