from typing import Any, List, Optional

from django.core.management.base import BaseCommand, CommandParser
from django.db.backends.sqlite3.base import DatabaseWrapper


class Command(BaseCommand):
    stderr: django.core.management.base.OutputWrapper
    stdout: django.core.management.base.OutputWrapper
    style: django.core.management.color.Style
    help: str = ...
    def add_arguments(self, parser: CommandParser) -> None: ...
    verbosity: Any = ...
    def handle(self, *args: Any, **options: Any) -> None: ...
    def show_list(
        self, connection: DatabaseWrapper, app_names: List[str] = ...
    ) -> None: ...
    def show_plan(
        self, connection: DatabaseWrapper, app_names: List[str] = ...
    ) -> None: ...
