from typing import Any, Optional

from django.core.management.base import BaseCommand, CommandParser

class Command(BaseCommand):
    stderr: django.core.management.base.OutputWrapper
    stdout: django.core.management.base.OutputWrapper
    style: django.core.management.color.Style
    help: str = ...
    output_transaction: bool = ...
    def add_arguments(self, parser: CommandParser) -> None: ...
    def execute(self, *args: Any, **options: Any) -> str: ...
    def handle(self, *args: Any, **options: Any) -> str: ...
