from typing import Any, Optional, Union

from django.core.management.base import BaseCommand, CommandParser
from django.db.models.fields import Field


class NotRunningInTTYException(Exception): ...

class Command(BaseCommand):
    stderr: django.core.management.base.OutputWrapper
    stdout: django.core.management.base.OutputWrapper
    style: django.core.management.color.Style
    help: str = ...
    requires_migrations_checks: bool = ...
    stealth_options: Any = ...
    UserModel: Any = ...
    username_field: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_arguments(self, parser: CommandParser) -> None: ...
    stdin: Any = ...
    def execute(self, *args: Any, **options: Any) -> None: ...
    def handle(self, *args: Any, **options: Any) -> None: ...
    def get_input_data(
        self, field: Field, message: str, default: Optional[str] = ...
    ) -> Optional[Union[int, str]]: ...
